/*******************************************************************************
 * Script      : CR-YYYY-XXX_01_ddl.sql
 * CR          : CR-YYYY-XXX  Karachi Transport Allowance & RFID Deduction
 * Design      : DS-01 to DS-06, DS-08 to DS-11, DS-13 (Design v0.1, DRAFT)
 * Requirements: SRS v0.3 (DRAFT)
 * Author      : Claude (AI draft) for Solution Architect
 * Date        : 2026-09-30
 * Description : Sequences, tables, constraints, indexes, comments and
 *               delete-protection triggers for the transport allowance module.
 *               Creates NEW objects only; no existing HRD object is altered.
 * Notes       : EMPLOYEE_ID columns have no foreign key yet. The employee
 *               master table is not confirmed (SRS Q-09, review RV-10). Add the
 *               FKs once it is.
 ******************************************************************************/
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

--------------------------------------------------------------------------------
-- Sequences
--------------------------------------------------------------------------------
CREATE SEQUENCE HRD.TRANSPORT_FORMULA_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.FUEL_PRICE_SEQ            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.TRANSPORT_TERMINAL_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.TRANSPORT_ELIGIBILITY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.TRANSPORT_EXEMPT_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.TRANSPORT_SWIPE_SEQ       START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HRD.TRANSPORT_TRIP_SEQ        START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HRD.TRANSPORT_ADJ_REQ_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.TRANSPORT_PERIOD_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.TRANSPORT_MONTHLY_SEQ     START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE HRD.TRANSPORT_NOTIFY_SEQ      START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HRD.TRANSPORT_AUDIT_SEQ       START WITH 1 INCREMENT BY 1 CACHE 20;

--------------------------------------------------------------------------------
-- DS-01  Policy / formula versions (all open business rules are settings here)
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_FORMULA_MST
(
    FORMULA_ID            NUMBER(10)     DEFAULT HRD.TRANSPORT_FORMULA_SEQ.NEXTVAL NOT NULL,
    VERSION_NO            NUMBER(5)      NOT NULL,
    EFFECTIVE_FROM        DATE           NOT NULL,
    ALLOWANCE_AMOUNT      NUMBER(10,2)   NOT NULL,
    ALLOWANCE_BASE_DAYS   NUMBER(2)      NOT NULL,
    FORMULA_TYPE          VARCHAR2(20)   DEFAULT 'FUEL_INDEXED' NOT NULL,
    BASE_TRIP_COST        NUMBER(10,2)   NOT NULL,
    REF_FUEL_PRICE        NUMBER(10,2)   NOT NULL,
    SETTLEMENT_MODE       VARCHAR2(20)   NOT NULL,
    PRORATION_MODE        VARCHAR2(20)   NOT NULL,
    DEDUCTION_BASIS       VARCHAR2(10)   NOT NULL,
    SINGLE_SWIPE_RULE     VARCHAR2(20)   NOT NULL,
    DIRECTION_MODE        VARCHAR2(10)   NOT NULL,
    ROUTING_MODE          VARCHAR2(20)   NOT NULL,
    LATE_PRICE_MODE       VARCHAR2(20)   DEFAULT 'RECALCULATE' NOT NULL,
    REPEAT_SWIPE_MINUTES  NUMBER(3)      DEFAULT 2 NOT NULL,
    ESCALATION_DAYS       NUMBER(2)      DEFAULT 2 NOT NULL,
    ADJ_WINDOW_DAYS       NUMBER(3),
    PAYROLL_CUTOFF_DAY    NUMBER(2),
    STATUS                VARCHAR2(10)   DEFAULT 'PENDING' NOT NULL,
    MAKER_BY              VARCHAR2(100)  NOT NULL,
    CHECKER_BY            VARCHAR2(100),
    CHECKED_ON            DATE,
    CREATED_BY            VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON            DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY           VARCHAR2(100),
    MODIFIED_ON           DATE,
    CONSTRAINT PK_HRD_TRANSPORT_FORMULA_MST PRIMARY KEY (FORMULA_ID),
    CONSTRAINT UK_TRFORMULA_VERSION UNIQUE (VERSION_NO),
    CONSTRAINT CK_TRFORMULA_AMOUNTS CHECK (ALLOWANCE_AMOUNT > 0 AND BASE_TRIP_COST > 0 AND REF_FUEL_PRICE > 0),
    CONSTRAINT CK_TRFORMULA_BASE_DAYS CHECK (ALLOWANCE_BASE_DAYS BETWEEN 1 AND 31),
    CONSTRAINT CK_TRFORMULA_TYPE CHECK (FORMULA_TYPE IN ('FUEL_INDEXED','FIXED')),
    CONSTRAINT CK_TRFORMULA_SETTLEMENT CHECK (SETTLEMENT_MODE IN ('CAP_ZERO','SCALE_ALLOWANCE','DERIVE_TRIP_COST','RECOVER_EXCESS')),
    CONSTRAINT CK_TRFORMULA_PRORATION CHECK (PRORATION_MODE IN ('NONE','CALENDAR_DAYS','WORKING_DAYS')),
    CONSTRAINT CK_TRFORMULA_BASIS CHECK (DEDUCTION_BASIS IN ('PER_TRIP','PER_SWIPE')),
    CONSTRAINT CK_TRFORMULA_SINGLE CHECK (SINGLE_SWIPE_RULE IN ('COUNT_TRIP','REVIEW')),
    CONSTRAINT CK_TRFORMULA_DIRECTION CHECK (DIRECTION_MODE IN ('TERMINAL','SEQUENCE')),
    CONSTRAINT CK_TRFORMULA_ROUTING CHECK (ROUTING_MODE IN ('SUPERVISOR','COORDINATOR','BOTH_FIRST_WINS')),
    CONSTRAINT CK_TRFORMULA_LATE_PRICE CHECK (LATE_PRICE_MODE IN ('RECALCULATE','FROM_ENTRY')),
    CONSTRAINT CK_TRFORMULA_REPEAT CHECK (REPEAT_SWIPE_MINUTES BETWEEN 0 AND 120),
    CONSTRAINT CK_TRFORMULA_ESCALATION CHECK (ESCALATION_DAYS BETWEEN 1 AND 30),
    CONSTRAINT CK_TRFORMULA_CUTOFF CHECK (PAYROLL_CUTOFF_DAY IS NULL OR PAYROLL_CUTOFF_DAY BETWEEN 1 AND 31),
    CONSTRAINT CK_TRFORMULA_STATUS CHECK (STATUS IN ('PENDING','ACTIVE','REJECTED','RETIRED')),
    CONSTRAINT CK_TRFORMULA_MAKER_CHECKER CHECK (CHECKER_BY IS NULL OR CHECKER_BY <> MAKER_BY)
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_FORMULA_MST IS 'Versioned transport allowance policy: allowance, deduction formula and the settings that implement open business rules (SRS Q-02, Q-04, Q-05, Q-07, Q-10, Q-11, Q-14, Q-15, Q-16). Maker-checker activation.';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_FORMULA_MST.BASE_TRIP_COST IS 'Per-trip cost at REF_FUEL_PRICE (reference 500 PKR). FUEL_INDEXED cost = ROUND(BASE_TRIP_COST * fuel price / REF_FUEL_PRICE).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_FORMULA_MST.SETTLEMENT_MODE IS 'SRS Q-07: CAP_ZERO (a), SCALE_ALLOWANCE (b), DERIVE_TRIP_COST (c), RECOVER_EXCESS (salary recovery, needs policy basis).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_FORMULA_MST.DIRECTION_MODE IS 'SRS Q-15: TERMINAL = direction fixed per reader; SEQUENCE = derived from the order of swipes.';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_FORMULA_MST.ROUTING_MODE IS 'SRS Q-11: who approves missed-swipe adjustments.';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_FORMULA_MST.LATE_PRICE_MODE IS 'SRS Q-16: RECALCULATE open-period trips when a price is activated late, or apply FROM_ENTRY only.';
CREATE UNIQUE INDEX HRD.IDX_TRFORMULA_ACTIVE_FROM ON HRD.HRD_TRANSPORT_FORMULA_MST (CASE WHEN STATUS = 'ACTIVE' THEN EFFECTIVE_FROM END);

--------------------------------------------------------------------------------
-- DS-02  Fuel price history (effective-dated, maker-checker)
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_FUEL_PRICE_HIS
(
    FUEL_PRICE_ID     NUMBER(10)     DEFAULT HRD.FUEL_PRICE_SEQ.NEXTVAL NOT NULL,
    PRICE_PER_LITRE   NUMBER(10,2)   NOT NULL,
    EFFECTIVE_FROM    DATE           NOT NULL,
    STATUS            VARCHAR2(10)   DEFAULT 'PENDING' NOT NULL,
    MAKER_BY          VARCHAR2(100)  NOT NULL,
    CHECKER_BY        VARCHAR2(100),
    CHECKED_ON        DATE,
    REMARKS           VARCHAR2(500),
    CREATED_BY        VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON        DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY       VARCHAR2(100),
    MODIFIED_ON       DATE,
    CONSTRAINT PK_HRD_FUEL_PRICE_HIS PRIMARY KEY (FUEL_PRICE_ID),
    CONSTRAINT CK_FUELPRICE_PRICE CHECK (PRICE_PER_LITRE > 0),
    CONSTRAINT CK_FUELPRICE_STATUS CHECK (STATUS IN ('PENDING','ACTIVE','REJECTED')),
    CONSTRAINT CK_FUELPRICE_MAKER_CHECKER CHECK (CHECKER_BY IS NULL OR CHECKER_BY <> MAKER_BY)
);
COMMENT ON TABLE HRD.HRD_FUEL_PRICE_HIS IS 'Fuel price per litre with effective date/time. The price for a trip is the latest ACTIVE row with EFFECTIVE_FROM <= trip time (SRS RULE-06).';
CREATE UNIQUE INDEX HRD.IDX_FUELPRICE_ACTIVE_FROM ON HRD.HRD_FUEL_PRICE_HIS (CASE WHEN STATUS = 'ACTIVE' THEN EFFECTIVE_FROM END);
CREATE INDEX HRD.IDX_FUELPRICE_STATUS_FROM ON HRD.HRD_FUEL_PRICE_HIS (STATUS, EFFECTIVE_FROM);

--------------------------------------------------------------------------------
-- DS-03  Terminals
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_TERMINAL_MST
(
    TERMINAL_ID          NUMBER(10)     DEFAULT HRD.TRANSPORT_TERMINAL_SEQ.NEXTVAL NOT NULL,
    TERMINAL_CODE        VARCHAR2(30)   NOT NULL,
    TERMINAL_NAME        VARCHAR2(100)  NOT NULL,
    LOCATION_CODE        VARCHAR2(30)   NOT NULL,
    TERMINAL_DIRECTION   VARCHAR2(10)   DEFAULT 'BOTH' NOT NULL,
    DEVICE_REF           VARCHAR2(100),
    IS_ACTIVE            CHAR(1)        DEFAULT 'Y' NOT NULL,
    LAST_SEEN_ON         DATE,
    CREATED_BY           VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON           DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY          VARCHAR2(100),
    MODIFIED_ON          DATE,
    CONSTRAINT PK_HRD_TRANSPORT_TERMINAL_MST PRIMARY KEY (TERMINAL_ID),
    CONSTRAINT UK_TRTERMINAL_CODE UNIQUE (TERMINAL_CODE),
    CONSTRAINT CK_TRTERMINAL_DIRECTION CHECK (TERMINAL_DIRECTION IN ('BOARDING','ALIGHTING','BOTH')),
    CONSTRAINT CK_TRTERMINAL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_TERMINAL_MST IS 'RFID transport terminals (KDC pickup point, hospital). LOCATION_CODE is free text so more stops can be added (SRS Q-01).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_TERMINAL_MST.TERMINAL_DIRECTION IS 'Used when DIRECTION_MODE = TERMINAL (separate readers per direction). BOTH when direction comes from swipe sequence.';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_TERMINAL_MST.LAST_SEEN_ON IS 'Last swipe or heartbeat received; drives the terminal-offline alert (NFR-OPS-01).';

--------------------------------------------------------------------------------
-- DS-04  Eligibility and exemptions
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_ELIGIBILITY_DTL
(
    ELIGIBILITY_ID   NUMBER(10)     DEFAULT HRD.TRANSPORT_ELIGIBILITY_SEQ.NEXTVAL NOT NULL,
    EMPLOYEE_ID      NUMBER(10)     NOT NULL,
    EFFECTIVE_FROM   DATE           NOT NULL,
    EFFECTIVE_TO     DATE,
    BUS_MANDATORY    CHAR(1)        DEFAULT 'Y' NOT NULL,
    REMARKS          VARCHAR2(500),
    CREATED_BY       VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON       DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY      VARCHAR2(100),
    MODIFIED_ON      DATE,
    CONSTRAINT PK_HRD_TRANSPORT_ELIGIBILITY PRIMARY KEY (ELIGIBILITY_ID),
    CONSTRAINT CK_TRELIG_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
    CONSTRAINT CK_TRELIG_MANDATORY CHECK (BUS_MANDATORY IN ('Y','N'))
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_ELIGIBILITY_DTL IS 'Transport allowance eligibility periods per employee (SRS FR-001). Overlap check in PKG_TRANSPORT_ALLOWANCE.P_SET_ELIGIBILITY.';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_ELIGIBILITY_DTL.BUS_MANDATORY IS 'SRS Q-03: Y = expected to use the bus, so days attended without trips are reported (FR-014).';
CREATE INDEX HRD.IDX_TRELIG_EMP_FROM ON HRD.HRD_TRANSPORT_ELIGIBILITY_DTL (EMPLOYEE_ID, EFFECTIVE_FROM);

CREATE TABLE HRD.HRD_TRANSPORT_EXEMPT_DTL
(
    EXEMPT_ID      NUMBER(10)     DEFAULT HRD.TRANSPORT_EXEMPT_SEQ.NEXTVAL NOT NULL,
    EMPLOYEE_ID    NUMBER(10)     NOT NULL,
    EXEMPT_FROM    DATE           NOT NULL,
    EXEMPT_TO      DATE           NOT NULL,
    REASON_CODE    VARCHAR2(20)   NOT NULL,
    REMARKS        VARCHAR2(500),
    APPROVED_BY    VARCHAR2(100)  NOT NULL,
    CREATED_BY     VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON     DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY    VARCHAR2(100),
    MODIFIED_ON    DATE,
    CONSTRAINT PK_HRD_TRANSPORT_EXEMPT_DTL PRIMARY KEY (EXEMPT_ID),
    CONSTRAINT CK_TREXEMPT_DATES CHECK (EXEMPT_TO >= EXEMPT_FROM),
    CONSTRAINT CK_TREXEMPT_REASON CHECK (REASON_CODE IN ('NO_BUS_SHIFT','OWN_TRANSPORT','OTHER'))
);
COMMENT ON TABLE HRD.HRD_TRANSPORT_EXEMPT_DTL IS 'Days excluded from the non-swipe report: shifts with no bus service or approved own transport (SRS FR-014 AC3, Q-17).';
CREATE INDEX HRD.IDX_TREXEMPT_EMP_FROM ON HRD.HRD_TRANSPORT_EXEMPT_DTL (EMPLOYEE_ID, EXEMPT_FROM);

--------------------------------------------------------------------------------
-- DS-09  Payroll periods (created before trips/monthly because they reference it)
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_PERIOD_MST
(
    PERIOD_ID       NUMBER(10)     DEFAULT HRD.TRANSPORT_PERIOD_SEQ.NEXTVAL NOT NULL,
    PERIOD_CODE     VARCHAR2(7)    NOT NULL,
    PERIOD_START    DATE           NOT NULL,
    PERIOD_END      DATE           NOT NULL,
    STATUS          VARCHAR2(10)   DEFAULT 'OPEN' NOT NULL,
    CLOSED_BY       VARCHAR2(100),
    CLOSED_ON       DATE,
    SENT_BY         VARCHAR2(100),
    SENT_ON         DATE,
    REOPEN_REASON   VARCHAR2(500),
    CREATED_BY      VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON      DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY     VARCHAR2(100),
    MODIFIED_ON     DATE,
    CONSTRAINT PK_HRD_TRANSPORT_PERIOD_MST PRIMARY KEY (PERIOD_ID),
    CONSTRAINT UK_TRPERIOD_CODE UNIQUE (PERIOD_CODE),
    CONSTRAINT CK_TRPERIOD_CODE CHECK (REGEXP_LIKE(PERIOD_CODE, '^[0-9]{4}-(0[1-9]|1[0-2])$')),
    CONSTRAINT CK_TRPERIOD_DATES CHECK (PERIOD_END >= PERIOD_START),
    CONSTRAINT CK_TRPERIOD_STATUS CHECK (STATUS IN ('OPEN','CLOSED','SENT','REOPENED'))
);
COMMENT ON TABLE HRD.HRD_TRANSPORT_PERIOD_MST IS 'Transport payroll months. OPEN -> CLOSED (calculated) -> SENT (to payroll). REOPENED only by Finance, audited (SRS FR-018 AC2).';

--------------------------------------------------------------------------------
-- DS-05  Swipes (raw, never deleted)
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_SWIPE_TRN
(
    SWIPE_ID          NUMBER(15)     DEFAULT HRD.TRANSPORT_SWIPE_SEQ.NEXTVAL NOT NULL,
    SOURCE_REF        VARCHAR2(100)  NOT NULL,
    CARD_NO           VARCHAR2(50)   NOT NULL,
    EMPLOYEE_ID       NUMBER(10),
    TERMINAL_ID       NUMBER(10)     NOT NULL,
    SWIPE_TIME        DATE           NOT NULL,
    RECEIVED_ON       DATE           DEFAULT SYSDATE NOT NULL,
    DIRECTION         VARCHAR2(10),
    SWIPE_STATUS      VARCHAR2(15)   NOT NULL,
    TRIP_ID           NUMBER(15),
    REVERSAL_REASON   VARCHAR2(500),
    CREATED_BY        VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON        DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY       VARCHAR2(100),
    MODIFIED_ON       DATE,
    CONSTRAINT PK_HRD_TRANSPORT_SWIPE_TRN PRIMARY KEY (SWIPE_ID),
    CONSTRAINT UK_TRSWIPE_SOURCE_REF UNIQUE (SOURCE_REF),
    CONSTRAINT FK_TRSWIPE_TERMINAL FOREIGN KEY (TERMINAL_ID) REFERENCES HRD.HRD_TRANSPORT_TERMINAL_MST (TERMINAL_ID),
    CONSTRAINT CK_TRSWIPE_DIRECTION CHECK (DIRECTION IS NULL OR DIRECTION IN ('BOARDING','ALIGHTING')),
    CONSTRAINT CK_TRSWIPE_STATUS CHECK (SWIPE_STATUS IN ('VALID','UNKNOWN_CARD','INACTIVE_CARD','NOT_ELIGIBLE','DUPLICATE','REVERSED'))
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_SWIPE_TRN IS 'Every RFID swipe received (SRS FR-003). Rows are never deleted (NFR-AUD-01); corrections set SWIPE_STATUS = REVERSED with a reason.';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_SWIPE_TRN.SOURCE_REF IS 'Unique reference from the terminal (device id + device sequence). Makes offline replays idempotent (NFR-AVL-01).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_SWIPE_TRN.SWIPE_TIME IS 'Time of the swipe at the terminal, not the time received.';
CREATE INDEX HRD.IDX_TRSWIPE_EMP_TIME ON HRD.HRD_TRANSPORT_SWIPE_TRN (EMPLOYEE_ID, SWIPE_TIME);
CREATE INDEX HRD.IDX_TRSWIPE_TERMINAL ON HRD.HRD_TRANSPORT_SWIPE_TRN (TERMINAL_ID);
CREATE INDEX HRD.IDX_TRSWIPE_TRIP ON HRD.HRD_TRANSPORT_SWIPE_TRN (TRIP_ID);
CREATE INDEX HRD.IDX_TRSWIPE_UNPROCESSED ON HRD.HRD_TRANSPORT_SWIPE_TRN (CASE WHEN TRIP_ID IS NULL AND SWIPE_STATUS = 'VALID' THEN SWIPE_TIME END);

--------------------------------------------------------------------------------
-- DS-08  Missed-swipe adjustment requests
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_ADJ_REQUEST
(
    ADJ_REQUEST_ID     NUMBER(10)     DEFAULT HRD.TRANSPORT_ADJ_REQ_SEQ.NEXTVAL NOT NULL,
    EMPLOYEE_ID        NUMBER(10)     NOT NULL,
    TRIP_DATE          DATE           NOT NULL,
    TRIP_DIRECTION     VARCHAR2(15)   NOT NULL,
    REASON             VARCHAR2(500)  NOT NULL,
    STATUS             VARCHAR2(10)   DEFAULT 'SUBMITTED' NOT NULL,
    APPROVER_ID        NUMBER(10),
    ESCALATED_ON       DATE,
    DECIDED_BY         VARCHAR2(100),
    DECIDED_ON         DATE,
    DECISION_COMMENT   VARCHAR2(500),
    ROW_VERSION        NUMBER(10)     DEFAULT 1 NOT NULL,
    CREATED_BY         VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON         DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY        VARCHAR2(100),
    MODIFIED_ON        DATE,
    CONSTRAINT PK_HRD_TRANSPORT_ADJ_REQUEST PRIMARY KEY (ADJ_REQUEST_ID),
    CONSTRAINT CK_TRADJ_DIRECTION CHECK (TRIP_DIRECTION IN ('KDC_TO_HOSP','HOSP_TO_KDC')),
    CONSTRAINT CK_TRADJ_REASON CHECK (LENGTH(TRIM(REASON)) >= 10),
    CONSTRAINT CK_TRADJ_STATUS CHECK (STATUS IN ('SUBMITTED','ESCALATED','APPROVED','REJECTED','CANCELLED')),
    CONSTRAINT CK_TRADJ_TRUNC_DATE CHECK (TRIP_DATE = TRUNC(TRIP_DATE))
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_ADJ_REQUEST IS 'Missed-swipe adjustment requests (SRS FR-011 to FR-013). ROW_VERSION enforces first-decision-wins (FR-013 AC4).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_ADJ_REQUEST.APPROVER_ID IS 'Current assignee (employee id). Changes to the transport coordinator on escalation (FR-012 AC3).';
CREATE UNIQUE INDEX HRD.IDX_TRADJ_OPEN_UNIQUE ON HRD.HRD_TRANSPORT_ADJ_REQUEST
    (CASE WHEN STATUS IN ('SUBMITTED','ESCALATED','APPROVED') THEN EMPLOYEE_ID END,
     CASE WHEN STATUS IN ('SUBMITTED','ESCALATED','APPROVED') THEN TRIP_DATE END,
     CASE WHEN STATUS IN ('SUBMITTED','ESCALATED','APPROVED') THEN TRIP_DIRECTION END);
CREATE INDEX HRD.IDX_TRADJ_APPROVER_STATUS ON HRD.HRD_TRANSPORT_ADJ_REQUEST (APPROVER_ID, STATUS);
CREATE INDEX HRD.IDX_TRADJ_EMP_DATE ON HRD.HRD_TRANSPORT_ADJ_REQUEST (EMPLOYEE_ID, TRIP_DATE);

--------------------------------------------------------------------------------
-- DS-06 / DS-07  Trips with their deduction
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_TRIP_TRN
(
    TRIP_ID            NUMBER(15)     DEFAULT HRD.TRANSPORT_TRIP_SEQ.NEXTVAL NOT NULL,
    EMPLOYEE_ID        NUMBER(10)     NOT NULL,
    PERIOD_ID          NUMBER(10)     NOT NULL,
    TRIP_DATE          DATE           NOT NULL,
    TRIP_DIRECTION     VARCHAR2(15)   NOT NULL,
    START_TIME         DATE,
    END_TIME           DATE,
    TRIP_SOURCE        VARCHAR2(10)   NOT NULL,
    TRIP_STATUS        VARCHAR2(15)   NOT NULL,
    FORMULA_ID         NUMBER(10),
    FUEL_PRICE_ID      NUMBER(10),
    FUEL_PRICE         NUMBER(10,2),
    DEDUCTION_AMOUNT   NUMBER(10,2),
    ADJ_REQUEST_ID     NUMBER(10),
    REVERSAL_REASON    VARCHAR2(500),
    CREATED_BY         VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON         DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY        VARCHAR2(100),
    MODIFIED_ON        DATE,
    CONSTRAINT PK_HRD_TRANSPORT_TRIP_TRN PRIMARY KEY (TRIP_ID),
    CONSTRAINT FK_TRTRIP_PERIOD FOREIGN KEY (PERIOD_ID) REFERENCES HRD.HRD_TRANSPORT_PERIOD_MST (PERIOD_ID),
    CONSTRAINT FK_TRTRIP_FORMULA FOREIGN KEY (FORMULA_ID) REFERENCES HRD.HRD_TRANSPORT_FORMULA_MST (FORMULA_ID),
    CONSTRAINT FK_TRTRIP_FUEL_PRICE FOREIGN KEY (FUEL_PRICE_ID) REFERENCES HRD.HRD_FUEL_PRICE_HIS (FUEL_PRICE_ID),
    CONSTRAINT FK_TRTRIP_ADJ_REQUEST FOREIGN KEY (ADJ_REQUEST_ID) REFERENCES HRD.HRD_TRANSPORT_ADJ_REQUEST (ADJ_REQUEST_ID),
    CONSTRAINT CK_TRTRIP_DIRECTION CHECK (TRIP_DIRECTION IN ('KDC_TO_HOSP','HOSP_TO_KDC','UNKNOWN')),
    CONSTRAINT CK_TRTRIP_SOURCE CHECK (TRIP_SOURCE IN ('RFID','MANUAL')),
    CONSTRAINT CK_TRTRIP_STATUS CHECK (TRIP_STATUS IN ('VALID','INCOMPLETE','RATE_MISSING','REVERSED')),
    CONSTRAINT CK_TRTRIP_AMOUNT CHECK (DEDUCTION_AMOUNT IS NULL OR DEDUCTION_AMOUNT >= 0),
    CONSTRAINT CK_TRTRIP_MANUAL_REF CHECK (TRIP_SOURCE = 'RFID' OR ADJ_REQUEST_ID IS NOT NULL)
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_TRIP_TRN IS 'Trips derived from swipes (RFID) or approved adjustments (MANUAL), with the deduction, fuel price and formula version used (SRS FR-006, FR-007, FR-013).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_TRIP_TRN.TRIP_STATUS IS 'VALID counts toward deductions. INCOMPLETE = single swipe awaiting review (Q-02). RATE_MISSING = no effective fuel price (FR-007 AC3).';
ALTER TABLE HRD.HRD_TRANSPORT_SWIPE_TRN ADD CONSTRAINT FK_TRSWIPE_TRIP FOREIGN KEY (TRIP_ID) REFERENCES HRD.HRD_TRANSPORT_TRIP_TRN (TRIP_ID);
CREATE INDEX HRD.IDX_TRTRIP_EMP_PERIOD ON HRD.HRD_TRANSPORT_TRIP_TRN (EMPLOYEE_ID, PERIOD_ID);
CREATE INDEX HRD.IDX_TRTRIP_PERIOD_STATUS ON HRD.HRD_TRANSPORT_TRIP_TRN (PERIOD_ID, TRIP_STATUS);
CREATE INDEX HRD.IDX_TRTRIP_FORMULA ON HRD.HRD_TRANSPORT_TRIP_TRN (FORMULA_ID);
CREATE INDEX HRD.IDX_TRTRIP_FUEL_PRICE ON HRD.HRD_TRANSPORT_TRIP_TRN (FUEL_PRICE_ID);
CREATE INDEX HRD.IDX_TRTRIP_ADJ_REQUEST ON HRD.HRD_TRANSPORT_TRIP_TRN (ADJ_REQUEST_ID);
CREATE UNIQUE INDEX HRD.IDX_TRTRIP_ONE_PER_LEG ON HRD.HRD_TRANSPORT_TRIP_TRN
    (CASE WHEN TRIP_STATUS <> 'REVERSED' AND TRIP_DIRECTION <> 'UNKNOWN' THEN EMPLOYEE_ID END,
     CASE WHEN TRIP_STATUS <> 'REVERSED' AND TRIP_DIRECTION <> 'UNKNOWN' THEN TRIP_DATE END,
     CASE WHEN TRIP_STATUS <> 'REVERSED' AND TRIP_DIRECTION <> 'UNKNOWN' THEN TRIP_DIRECTION END,
     CASE WHEN TRIP_STATUS <> 'REVERSED' AND TRIP_DIRECTION <> 'UNKNOWN' THEN START_TIME END);

--------------------------------------------------------------------------------
-- DS-09  Monthly settlement per employee
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_MONTHLY_DTL
(
    MONTHLY_ID                NUMBER(10)     DEFAULT HRD.TRANSPORT_MONTHLY_SEQ.NEXTVAL NOT NULL,
    PERIOD_ID                 NUMBER(10)     NOT NULL,
    EMPLOYEE_ID               NUMBER(10)     NOT NULL,
    FORMULA_ID                NUMBER(10)     NOT NULL,
    ELIGIBLE_DAYS             NUMBER(3)      NOT NULL,
    WORKING_DAYS              NUMBER(3)      NOT NULL,
    ALLOWANCE_AMOUNT          NUMBER(10,2)   NOT NULL,
    TRIP_COUNT                NUMBER(5)      NOT NULL,
    TOTAL_DEDUCTION           NUMBER(10,2)   NOT NULL,
    PRIOR_PERIOD_CORRECTION   NUMBER(10,2)   DEFAULT 0 NOT NULL,
    EXCESS_AMOUNT             NUMBER(10,2)   DEFAULT 0 NOT NULL,
    PAYOUT_AMOUNT             NUMBER(10,2)   NOT NULL,
    FINANCE_REVIEW_FLAG       CHAR(1)        DEFAULT 'N' NOT NULL,
    CREATED_BY                VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON                DATE           DEFAULT SYSDATE NOT NULL,
    MODIFIED_BY               VARCHAR2(100),
    MODIFIED_ON               DATE,
    CONSTRAINT PK_HRD_TRANSPORT_MONTHLY_DTL PRIMARY KEY (MONTHLY_ID),
    CONSTRAINT UK_TRMONTHLY_PERIOD_EMP UNIQUE (PERIOD_ID, EMPLOYEE_ID),
    CONSTRAINT FK_TRMONTHLY_PERIOD FOREIGN KEY (PERIOD_ID) REFERENCES HRD.HRD_TRANSPORT_PERIOD_MST (PERIOD_ID),
    CONSTRAINT FK_TRMONTHLY_FORMULA FOREIGN KEY (FORMULA_ID) REFERENCES HRD.HRD_TRANSPORT_FORMULA_MST (FORMULA_ID),
    CONSTRAINT CK_TRMONTHLY_REVIEW CHECK (FINANCE_REVIEW_FLAG IN ('Y','N')),
    CONSTRAINT CK_TRMONTHLY_AMOUNTS CHECK (ALLOWANCE_AMOUNT >= 0 AND TOTAL_DEDUCTION >= 0 AND EXCESS_AMOUNT >= 0)
);
COMMENT ON TABLE  HRD.HRD_TRANSPORT_MONTHLY_DTL IS 'Monthly allowance, deductions and payout per employee; the payroll register (SRS FR-010, FR-018).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_MONTHLY_DTL.PAYOUT_AMOUNT IS 'Amount passed to payroll. Negative only when SETTLEMENT_MODE = RECOVER_EXCESS (salary recovery).';
COMMENT ON COLUMN HRD.HRD_TRANSPORT_MONTHLY_DTL.PRIOR_PERIOD_CORRECTION IS 'Adjustments approved after an earlier period was sent to payroll (FR-018 AC3). Positive = extra deduction.';
CREATE INDEX HRD.IDX_TRMONTHLY_FORMULA ON HRD.HRD_TRANSPORT_MONTHLY_DTL (FORMULA_ID);
CREATE INDEX HRD.IDX_TRMONTHLY_EMP ON HRD.HRD_TRANSPORT_MONTHLY_DTL (EMPLOYEE_ID);

--------------------------------------------------------------------------------
-- DS-11  Notifications (read by the employee dashboard)
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_NOTIFY_LOG
(
    NOTIFY_ID        NUMBER(15)      DEFAULT HRD.TRANSPORT_NOTIFY_SEQ.NEXTVAL NOT NULL,
    EMPLOYEE_ID      NUMBER(10),
    RECIPIENT_ROLE   VARCHAR2(30),
    NOTIFY_TYPE      VARCHAR2(20)    NOT NULL,
    REF_ID           NUMBER(15),
    MESSAGE_TEXT     VARCHAR2(1000)  NOT NULL,
    IS_READ          CHAR(1)         DEFAULT 'N' NOT NULL,
    CREATED_BY       VARCHAR2(100)   DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    CREATED_ON       DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HRD_TRANSPORT_NOTIFY_LOG PRIMARY KEY (NOTIFY_ID),
    CONSTRAINT CK_TRNOTIFY_TARGET CHECK (EMPLOYEE_ID IS NOT NULL OR RECIPIENT_ROLE IS NOT NULL),
    CONSTRAINT CK_TRNOTIFY_TYPE CHECK (NOTIFY_TYPE IN ('SWIPE','ADJ_PENDING','ADJ_DECISION','ADJ_ESCALATED','RATE_MISSING','TERMINAL_OFFLINE')),
    CONSTRAINT CK_TRNOTIFY_READ CHECK (IS_READ IN ('Y','N'))
);
COMMENT ON TABLE HRD.HRD_TRANSPORT_NOTIFY_LOG IS 'Dashboard notifications (SRS FR-015) and role alerts (Finance rate-missing, terminal offline). The dashboard (SRS Q-13) reads unread rows.';
CREATE INDEX HRD.IDX_TRNOTIFY_EMP_UNREAD ON HRD.HRD_TRANSPORT_NOTIFY_LOG (EMPLOYEE_ID, IS_READ, CREATED_ON);
CREATE INDEX HRD.IDX_TRNOTIFY_ROLE_UNREAD ON HRD.HRD_TRANSPORT_NOTIFY_LOG (RECIPIENT_ROLE, IS_READ);

--------------------------------------------------------------------------------
-- DS-13  Audit log
--------------------------------------------------------------------------------
CREATE TABLE HRD.HRD_TRANSPORT_AUDIT_LOG
(
    AUDIT_ID      NUMBER(15)     DEFAULT HRD.TRANSPORT_AUDIT_SEQ.NEXTVAL NOT NULL,
    ENTITY_NAME   VARCHAR2(50)   NOT NULL,
    ENTITY_ID     NUMBER(15)     NOT NULL,
    ACTION_CODE   VARCHAR2(20)   NOT NULL,
    OLD_VALUE     CLOB,
    NEW_VALUE     CLOB,
    REASON        VARCHAR2(500),
    ACTION_BY     VARCHAR2(100)  DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER) NOT NULL,
    ACTION_ON     DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HRD_TRANSPORT_AUDIT_LOG PRIMARY KEY (AUDIT_ID),
    CONSTRAINT CK_TRAUDIT_OLD_JSON CHECK (OLD_VALUE IS JSON),
    CONSTRAINT CK_TRAUDIT_NEW_JSON CHECK (NEW_VALUE IS JSON)
);
COMMENT ON TABLE HRD.HRD_TRANSPORT_AUDIT_LOG IS 'Who/when/old/new for price, formula, eligibility, exemption, adjustment, reversal and period reopen actions (SRS NFR-AUD-01). OLD/NEW values are JSON.';
CREATE INDEX HRD.IDX_TRAUDIT_ENTITY ON HRD.HRD_TRANSPORT_AUDIT_LOG (ENTITY_NAME, ENTITY_ID);
CREATE INDEX HRD.IDX_TRAUDIT_ACTION_ON ON HRD.HRD_TRANSPORT_AUDIT_LOG (ACTION_ON);

--------------------------------------------------------------------------------
-- DS-13  Delete protection: swipes and trips are reversed, never deleted
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER HRD.TRG_TRANSPORT_SWIPE_BD
BEFORE DELETE ON HRD.HRD_TRANSPORT_SWIPE_TRN
BEGIN
    RAISE_APPLICATION_ERROR(-20720, 'Transport swipes cannot be deleted. Reverse the swipe with a reason instead.');
END TRG_TRANSPORT_SWIPE_BD;
/

CREATE OR REPLACE TRIGGER HRD.TRG_TRANSPORT_TRIP_BD
BEFORE DELETE ON HRD.HRD_TRANSPORT_TRIP_TRN
BEGIN
    RAISE_APPLICATION_ERROR(-20721, 'Transport trips cannot be deleted. Reverse the trip with a reason instead.');
END TRG_TRANSPORT_TRIP_BD;
/

-- Verification
SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM   ALL_OBJECTS
WHERE  OWNER = 'HRD'
AND   (OBJECT_NAME LIKE 'HRD\_TRANSPORT\_%' ESCAPE '\'
       OR OBJECT_NAME = 'HRD_FUEL_PRICE_HIS'
       OR OBJECT_NAME LIKE 'TRANSPORT\_%\_SEQ' ESCAPE '\'
       OR OBJECT_NAME = 'FUEL_PRICE_SEQ'
       OR OBJECT_NAME LIKE 'TRG\_TRANSPORT\_%' ESCAPE '\')
ORDER  BY OBJECT_TYPE, OBJECT_NAME;
