-- CR-YYYY-XXX_05_views.sql : views (Design v0.1, DRAFT). Run after both packages (views depend on PKG_LEAVE_SECURITY).
SET DEFINE OFF

CREATE OR REPLACE VIEW HRD.VW_PENDING_LEAVES AS
SELECT R.LEAVE_REQUEST_ID,
       E.EMP_NAME,
       R.EMPLOYEE_ID,
       R.LEAVE_TYPE,
       T.LEAVE_TYPE_NAME,
       R.FROM_DATE,
       R.TO_DATE,
       R.NO_OF_DAYS,
       W.WARD_NAME,
       R.ASSIGNED_APPROVER_ID,
       R.ROUTED_AS,
       R.CREATED_ON AS SUBMITTED_ON,
       R.ROW_VERSION,
       CASE WHEN EXISTS (SELECT 1 FROM HRD.HRD_LEAVE_ATTACHMENT_DTL A
                          WHERE A.LEAVE_REQUEST_ID = R.LEAVE_REQUEST_ID) THEN 'Y' ELSE 'N' END AS HAS_CERTIFICATE
  FROM HRD.HRD_LEAVE_REQUEST R
  JOIN HRD.HRD_EMPLOYEE_MST E ON E.EMPLOYEE_ID = R.EMPLOYEE_ID
  LEFT JOIN HRD.HRD_LEAVE_TYPE_MST T ON T.LEAVE_TYPE = R.LEAVE_TYPE
  LEFT JOIN HRD.HRD_WARD_MST W ON W.WARD_ID = R.WARD_ID
 WHERE R.STATUS = 'SUBMITTED'
   AND R.ASSIGNED_APPROVER_ID = (SELECT HRD.PKG_LEAVE_SECURITY.F_CURRENT_EMPLOYEE_ID FROM DUAL);
/

CREATE OR REPLACE VIEW HRD.VW_LEAVE_WARD_REPORT AS
SELECT R.LEAVE_REQUEST_ID,
       NVL(W.WARD_NAME, '(No ward)')   AS WARD_NAME,
       R.WARD_ID,
       R.EMPLOYEE_ID,
       E.EMP_NAME,
       R.LEAVE_TYPE,
       T.LEAVE_TYPE_NAME,
       TRUNC(R.FROM_DATE)              AS FROM_DATE,
       TRUNC(R.TO_DATE)                AS TO_DATE,
       R.NO_OF_DAYS,
       R.APPROVED_ON
  FROM HRD.HRD_LEAVE_REQUEST R
  JOIN HRD.HRD_EMPLOYEE_MST E ON E.EMPLOYEE_ID = R.EMPLOYEE_ID
  LEFT JOIN HRD.HRD_LEAVE_TYPE_MST T ON T.LEAVE_TYPE = R.LEAVE_TYPE
  LEFT JOIN HRD.HRD_WARD_MST W ON W.WARD_ID = R.WARD_ID
 WHERE R.STATUS = 'APPROVED'
   AND (SELECT HRD.PKG_LEAVE_SECURITY.F_CAN_VIEW_REPORT FROM DUAL) = 'Y';

