-- CR-YYYY-XXX_99_rollback.sql : rollback for Design v0.1 (DRAFT). Run steps in this order.
-- WARNING: dropping the new tables/columns destroys leave requests' new data, certificates and audit events
-- created after go-live. Export them first (Data Pump of the new tables + CTAS copy of HRD_LEAVE_REQUEST).
-- Roll back the APEX application FIRST by re-importing the pre-deployment export of application 200.
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

-- R1. Views and packages back to the snapshot definitions (evidence: mock_schema/tables/hrd_leave_request.sql, packages/*)
CREATE OR REPLACE VIEW HRD.VW_PENDING_LEAVES AS
SELECT R.LEAVE_REQUEST_ID, E.EMP_NAME FROM HRD_LEAVE_REQUEST R JOIN HRD_EMPLOYEE_MST E ON E.EMPLOYEE_ID = R.EMPLOYEE_ID WHERE R.STATUS='SUBMITTED';
DROP VIEW HRD.VW_LEAVE_WARD_REPORT;

CREATE OR REPLACE PACKAGE HRD.PKG_LEAVE_MANAGEMENT AS
  PROCEDURE P_SUBMIT_LEAVE (P_EMPLOYEE_ID IN NUMBER, P_LEAVE_TYPE IN VARCHAR2, P_FROM IN DATE, P_TO IN DATE);
  FUNCTION F_LEAVE_BALANCE (P_EMPLOYEE_ID IN NUMBER, P_LEAVE_TYPE IN VARCHAR2) RETURN NUMBER;
END PKG_LEAVE_MANAGEMENT;
/
CREATE OR REPLACE PACKAGE BODY HRD.PKG_LEAVE_MANAGEMENT AS
  PROCEDURE P_SUBMIT_LEAVE (P_EMPLOYEE_ID IN NUMBER, P_LEAVE_TYPE IN VARCHAR2, P_FROM IN DATE, P_TO IN DATE) IS
  BEGIN
    INSERT INTO HRD_LEAVE_REQUEST (EMPLOYEE_ID, LEAVE_TYPE, FROM_DATE, TO_DATE) VALUES (P_EMPLOYEE_ID, P_LEAVE_TYPE, P_FROM, P_TO);
  END;
  FUNCTION F_LEAVE_BALANCE (P_EMPLOYEE_ID IN NUMBER, P_LEAVE_TYPE IN VARCHAR2) RETURN NUMBER IS BEGIN RETURN 0; END;
END PKG_LEAVE_MANAGEMENT;
/
DROP PACKAGE HRD.PKG_LEAVE_SECURITY;

-- R2. Triggers: restore the original BI trigger, drop the new ones
CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_REQUEST_BI BEFORE INSERT ON HRD.HRD_LEAVE_REQUEST FOR EACH ROW
BEGIN :NEW.LEAVE_REQUEST_ID := NVL(:NEW.LEAVE_REQUEST_ID, LEAVE_REQ_SEQ.NEXTVAL); END;
/
DROP TRIGGER HRD.TRG_LEAVE_REQUEST_BU;
DROP TRIGGER HRD.TRG_LEAVE_REQUEST_BD;

-- R3. New tables (children first)
DROP TABLE HRD.HRD_LEAVE_AUDIT_LOG PURGE;
DROP TABLE HRD.HRD_LEAVE_ATTACHMENT_DTL PURGE;
DROP TABLE HRD.HRD_LEAVE_BALANCE_MST PURGE;
DROP TABLE HRD.HRD_LEAVE_ROLE_DTL PURGE;
DROP TABLE HRD.HRD_APP_USER_MST PURGE;

-- R4. Columns added to existing tables (constraints and indexes on them go with CASCADE CONSTRAINTS)
DROP INDEX HRD.IDX_LVREQ_EMP_FROM;
DROP INDEX HRD.IDX_LVREQ_APPR_STATUS;
DROP INDEX HRD.IDX_LVREQ_WARD_FROM;
DROP INDEX HRD.IDX_LVREQ_STATUS_DATES;
ALTER TABLE HRD.HRD_LEAVE_REQUEST DROP CONSTRAINT FK_LVREQ_TYPE;
ALTER TABLE HRD.HRD_LEAVE_REQUEST DROP CONSTRAINT CK_LVREQ_STATUS;
ALTER TABLE HRD.HRD_LEAVE_REQUEST DROP CONSTRAINT CK_LVREQ_DATES;
ALTER TABLE HRD.HRD_LEAVE_REQUEST DROP CONSTRAINT CK_LVREQ_ROUTED;
ALTER TABLE HRD.HRD_LEAVE_REQUEST DROP (NO_OF_DAYS, WARD_ID, ASSIGNED_APPROVER_ID, ROUTED_AS, DECISION_REMARKS,
  CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, ROW_VERSION) CASCADE CONSTRAINTS;
DROP INDEX HRD.IDX_EMP_WARD;
ALTER TABLE HRD.HRD_EMPLOYEE_MST DROP (WARD_ID) CASCADE CONSTRAINTS;

-- R5. Remaining new tables and sequences
DROP TABLE HRD.HRD_WARD_MST PURGE;
DROP TABLE HRD.HRD_LEAVE_CONFIG_MST PURGE;
DROP TABLE HRD.HRD_LEAVE_TYPE_MST PURGE;
DROP SEQUENCE HRD.WARD_SEQ;
DROP SEQUENCE HRD.LEAVE_CONFIG_SEQ;
DROP SEQUENCE HRD.LEAVE_ATTACHMENT_SEQ;
DROP SEQUENCE HRD.LEAVE_BALANCE_SEQ;
DROP SEQUENCE HRD.LEAVE_AUDIT_SEQ;
DROP SEQUENCE HRD.APP_USER_SEQ;
DROP SEQUENCE HRD.LEAVE_ROLE_SEQ;
-- LEAVE_REQ_SEQ is intentionally NOT dropped: the original trigger needs it.
