-- CR-YYYY-XXX_01_ddl.sql : DDL for mobile leave application (Design v0.1, DRAFT)
-- Target: Oracle 19c+, schema HRD. Run as HRD (or a DBA with ALTER SESSION SET CURRENT_SCHEMA=HRD).
-- Re-runnable: CREATE TABLE/SEQUENCE are NOT guarded (run once; use 00 pre-check in Design section 12).
--              ALTERs, constraints and indexes on existing tables are guarded.
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

------------------------------------------------------------------------------
-- 1. Sequences (DS-10)
------------------------------------------------------------------------------
-- LEAVE_REQ_SEQ is used by the existing TRG_LEAVE_REQUEST_BI but is absent from the schema snapshot (Q-15).
DECLARE
  V_CNT   NUMBER;
  V_START NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_CNT FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER = 'HRD' AND SEQUENCE_NAME = 'LEAVE_REQ_SEQ';
  IF V_CNT = 0 THEN
    SELECT NVL(MAX(LEAVE_REQUEST_ID), 0) + 1 INTO V_START FROM HRD.HRD_LEAVE_REQUEST;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE HRD.LEAVE_REQ_SEQ START WITH ' || TO_CHAR(V_START) || ' INCREMENT BY 1 NOCYCLE';
  END IF;
END;
/
CREATE SEQUENCE HRD.WARD_SEQ             START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.LEAVE_CONFIG_SEQ     START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.LEAVE_ATTACHMENT_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.LEAVE_BALANCE_SEQ    START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.LEAVE_AUDIT_SEQ      START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.APP_USER_SEQ         START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.LEAVE_ROLE_SEQ       START WITH 1 INCREMENT BY 1 NOCYCLE;

------------------------------------------------------------------------------
-- 2. New tables
------------------------------------------------------------------------------
-- DS-01 leave type master (holds policy parameters: RULE-03, RULE-04)
CREATE TABLE HRD.HRD_LEAVE_TYPE_MST (
  LEAVE_TYPE               VARCHAR2(3)   NOT NULL,
  LEAVE_TYPE_NAME          VARCHAR2(60)  NOT NULL,
  IS_ACTIVE                VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  MAX_DAYS_PER_REQUEST     NUMBER(3),
  CERT_REQUIRED_OVER_DAYS  NUMBER(3),
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_LEAVE_TYPE_MST PRIMARY KEY (LEAVE_TYPE),
  CONSTRAINT CK_LVTYPE_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CK_LVTYPE_MAXDAYS CHECK (MAX_DAYS_PER_REQUEST IS NULL OR MAX_DAYS_PER_REQUEST > 0),
  CONSTRAINT CK_LVTYPE_CERTDAYS CHECK (CERT_REQUIRED_OVER_DAYS IS NULL OR CERT_REQUIRED_OVER_DAYS >= 0)
);
COMMENT ON TABLE  HRD.HRD_LEAVE_TYPE_MST IS 'Leave types and per-type policy parameters';
COMMENT ON COLUMN HRD.HRD_LEAVE_TYPE_MST.LEAVE_TYPE IS 'Leave type code; same domain as HRD_LEAVE_REQUEST.LEAVE_TYPE';
COMMENT ON COLUMN HRD.HRD_LEAVE_TYPE_MST.MAX_DAYS_PER_REQUEST IS 'Max days in one request (casual leave = 3, RULE-04); NULL = no limit';
COMMENT ON COLUMN HRD.HRD_LEAVE_TYPE_MST.CERT_REQUIRED_OVER_DAYS IS 'Medical certificate required when days > this value (sick leave = 2, RULE-03); NULL = never required';

-- DS-02 leave configuration (key/value)
CREATE TABLE HRD.HRD_LEAVE_CONFIG_MST (
  LEAVE_CONFIG_ID  NUMBER(6)      NOT NULL,
  CONFIG_KEY       VARCHAR2(50)   NOT NULL,
  CONFIG_VALUE     VARCHAR2(200)  NOT NULL,
  DESCRIPTION      VARCHAR2(300),
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_LEAVE_CONFIG_MST PRIMARY KEY (LEAVE_CONFIG_ID),
  CONSTRAINT UK_LVCFG_KEY UNIQUE (CONFIG_KEY)
);
COMMENT ON TABLE  HRD.HRD_LEAVE_CONFIG_MST IS 'Leave module parameters (routing mode, DNS employee, certificate limits)';
COMMENT ON COLUMN HRD.HRD_LEAVE_CONFIG_MST.CONFIG_KEY IS 'ROUTING_MODE, DNS_EMPLOYEE_ID, CERT_ALLOWED_MIME, CERT_MAX_BYTES, BALANCE_COUNTS_PENDING, REJECT_REMARKS_MANDATORY';

-- DS-03 ward master
CREATE TABLE HRD.HRD_WARD_MST (
  WARD_ID        NUMBER(6)      NOT NULL,
  WARD_NAME      VARCHAR2(100)  NOT NULL,
  HEAD_NURSE_ID  NUMBER(10),
  IS_ACTIVE      VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_WARD_MST PRIMARY KEY (WARD_ID),
  CONSTRAINT UK_WARD_NAME UNIQUE (WARD_NAME),
  CONSTRAINT FK_WARD_HEAD FOREIGN KEY (HEAD_NURSE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
  CONSTRAINT CK_WARD_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
COMMENT ON TABLE  HRD.HRD_WARD_MST IS 'Nursing wards and their head nurse';
COMMENT ON COLUMN HRD.HRD_WARD_MST.HEAD_NURSE_ID IS 'Employee who is head nurse of the ward (one per ward)';
CREATE INDEX HRD.IDX_WARD_HEAD ON HRD.HRD_WARD_MST (HEAD_NURSE_ID);

-- DS-06 certificate / attachment storage
CREATE TABLE HRD.HRD_LEAVE_ATTACHMENT_DTL (
  LEAVE_ATTACHMENT_ID  NUMBER(12)     NOT NULL,
  LEAVE_REQUEST_ID     NUMBER(12)     NOT NULL,
  FILE_NAME            VARCHAR2(255)  NOT NULL,
  MIME_TYPE            VARCHAR2(100)  NOT NULL,
  FILE_SIZE            NUMBER(12)     NOT NULL,
  FILE_CONTENT         BLOB           NOT NULL,
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_LEAVE_ATTACHMENT_DTL PRIMARY KEY (LEAVE_ATTACHMENT_ID),
  CONSTRAINT FK_LVATT_REQ FOREIGN KEY (LEAVE_REQUEST_ID) REFERENCES HRD.HRD_LEAVE_REQUEST (LEAVE_REQUEST_ID),
  CONSTRAINT CK_LVATT_SIZE CHECK (FILE_SIZE > 0)
) LOB (FILE_CONTENT) STORE AS SECUREFILE (DISABLE STORAGE IN ROW);
COMMENT ON TABLE  HRD.HRD_LEAVE_ATTACHMENT_DTL IS 'Medical certificates attached to leave requests (personal health data)';
CREATE INDEX HRD.IDX_LVATT_REQ ON HRD.HRD_LEAVE_ATTACHMENT_DTL (LEAVE_REQUEST_ID);

-- DS-07 leave balance / entitlement
CREATE TABLE HRD.HRD_LEAVE_BALANCE_MST (
  LEAVE_BALANCE_ID  NUMBER(12)    NOT NULL,
  EMPLOYEE_ID       NUMBER(10)    NOT NULL,
  LEAVE_TYPE        VARCHAR2(3)   NOT NULL,
  BALANCE_YEAR      NUMBER(4)     NOT NULL,
  ENTITLED_DAYS     NUMBER(5,1)   NOT NULL,
  CARRIED_FWD_DAYS  NUMBER(5,1)   DEFAULT 0 NOT NULL,
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_LEAVE_BALANCE_MST PRIMARY KEY (LEAVE_BALANCE_ID),
  CONSTRAINT UK_LVBAL_EMP_TYPE_YR UNIQUE (EMPLOYEE_ID, LEAVE_TYPE, BALANCE_YEAR),
  CONSTRAINT FK_LVBAL_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
  CONSTRAINT FK_LVBAL_TYPE FOREIGN KEY (LEAVE_TYPE) REFERENCES HRD.HRD_LEAVE_TYPE_MST (LEAVE_TYPE),
  CONSTRAINT CK_LVBAL_DAYS CHECK (ENTITLED_DAYS >= 0 AND CARRIED_FWD_DAYS >= 0)
);
COMMENT ON TABLE  HRD.HRD_LEAVE_BALANCE_MST IS 'Yearly leave entitlement per employee and leave type (rules pending HR policy, Q-07)';
COMMENT ON COLUMN HRD.HRD_LEAVE_BALANCE_MST.ENTITLED_DAYS IS 'Days granted for BALANCE_YEAR; balance = entitled + carried forward - days taken';
CREATE INDEX HRD.IDX_LVBAL_TYPE ON HRD.HRD_LEAVE_BALANCE_MST (LEAVE_TYPE);

-- DS-08 audit log (append-only)
CREATE TABLE HRD.HRD_LEAVE_AUDIT_LOG (
  LEAVE_AUDIT_ID       NUMBER(12)     NOT NULL,
  LEAVE_REQUEST_ID     NUMBER(12)     NOT NULL,
  LEAVE_ATTACHMENT_ID  NUMBER(12),
  EVENT_TYPE           VARCHAR2(20)   NOT NULL,
  OLD_STATUS           VARCHAR2(10),
  NEW_STATUS           VARCHAR2(10),
  EVENT_BY             VARCHAR2(100)  NOT NULL,
  EVENT_EMPLOYEE_ID    NUMBER(10),
  EVENT_ON             TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  REMARKS              VARCHAR2(500),
  CREATED_BY           VARCHAR2(100)  NOT NULL,
  CREATED_ON           DATE           NOT NULL,
  CONSTRAINT PK_HRD_LEAVE_AUDIT_LOG PRIMARY KEY (LEAVE_AUDIT_ID),
  CONSTRAINT FK_LVAUD_REQ FOREIGN KEY (LEAVE_REQUEST_ID) REFERENCES HRD.HRD_LEAVE_REQUEST (LEAVE_REQUEST_ID),
  CONSTRAINT FK_LVAUD_ATT FOREIGN KEY (LEAVE_ATTACHMENT_ID) REFERENCES HRD.HRD_LEAVE_ATTACHMENT_DTL (LEAVE_ATTACHMENT_ID),
  CONSTRAINT CK_LVAUD_EVENT CHECK (EVENT_TYPE IN ('SUBMIT','APPROVE','REJECT','CERT_VIEW'))
);
COMMENT ON TABLE  HRD.HRD_LEAVE_AUDIT_LOG IS 'Who submitted, approved, rejected a leave request or viewed a certificate, and when (NFR-AUD-01); append-only';
CREATE INDEX HRD.IDX_LVAUD_REQ ON HRD.HRD_LEAVE_AUDIT_LOG (LEAVE_REQUEST_ID, EVENT_ON);
CREATE INDEX HRD.IDX_LVAUD_ATT ON HRD.HRD_LEAVE_AUDIT_LOG (LEAVE_ATTACHMENT_ID);

-- DS-09 login-to-employee mapping (PROVISIONAL: skip if the HRD schema already has one, Q-18)
CREATE TABLE HRD.HRD_APP_USER_MST (
  APP_USER_ID  NUMBER(10)     NOT NULL,
  USER_NAME    VARCHAR2(100)  NOT NULL,
  EMPLOYEE_ID  NUMBER(10)     NOT NULL,
  IS_ACTIVE    VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_APP_USER_MST PRIMARY KEY (APP_USER_ID),
  CONSTRAINT UK_APPUSER_NAME UNIQUE (USER_NAME),
  CONSTRAINT UK_APPUSER_EMP UNIQUE (EMPLOYEE_ID),
  CONSTRAINT FK_APPUSER_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
  CONSTRAINT CK_APPUSER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CK_APPUSER_UPPER CHECK (USER_NAME = UPPER(USER_NAME))
);
COMMENT ON TABLE  HRD.HRD_APP_USER_MST IS 'Maps APEX login name (upper case) to employee';

CREATE TABLE HRD.HRD_LEAVE_ROLE_DTL (
  LEAVE_ROLE_ID  NUMBER(10)    NOT NULL,
  EMPLOYEE_ID    NUMBER(10)    NOT NULL,
  ROLE_CODE      VARCHAR2(20)  NOT NULL,
  CREATED_BY       VARCHAR2(100) NOT NULL,
  CREATED_ON       DATE NOT NULL,
  MODIFIED_BY      VARCHAR2(100),
  MODIFIED_ON      DATE,
  CONSTRAINT PK_HRD_LEAVE_ROLE_DTL PRIMARY KEY (LEAVE_ROLE_ID),
  CONSTRAINT UK_LVROLE_EMP_ROLE UNIQUE (EMPLOYEE_ID, ROLE_CODE),
  CONSTRAINT FK_LVROLE_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
  CONSTRAINT CK_LVROLE_CODE CHECK (ROLE_CODE IN ('HR_USER','REPORT_VIEWER'))
);
COMMENT ON TABLE  HRD.HRD_LEAVE_ROLE_DTL IS 'HR and report-viewer roles for the leave module (approver roles derive from ward head / DNS)';
COMMENT ON COLUMN HRD.HRD_LEAVE_ROLE_DTL.ROLE_CODE IS 'HR_USER = all requests, certificates, report; REPORT_VIEWER = ward report only';

------------------------------------------------------------------------------
-- 3. Existing tables (guarded, re-runnable)
------------------------------------------------------------------------------
DECLARE
  PROCEDURE P_ADD_COL (P_TABLE IN VARCHAR2, P_COL IN VARCHAR2, P_DEF IN VARCHAR2) IS
    V_CNT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO V_CNT FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'HRD' AND TABLE_NAME = P_TABLE AND COLUMN_NAME = P_COL;
    IF V_CNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE HRD.' || P_TABLE || ' ADD (' || P_COL || ' ' || P_DEF || ')';
    END IF;
  END P_ADD_COL;
  PROCEDURE P_TRY (P_SQL IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE P_SQL;
  EXCEPTION
    WHEN OTHERS THEN
      -- ignore "already exists" style errors so the script can be re-run
      IF SQLCODE NOT IN (-955, -1408, -2260, -2261, -2264, -2275) THEN RAISE; END IF;
  END P_TRY;
BEGIN
  -- DS-04 HRD_EMPLOYEE_MST
  P_ADD_COL('HRD_EMPLOYEE_MST', 'WARD_ID', 'NUMBER(6)');
  P_TRY('ALTER TABLE HRD.HRD_EMPLOYEE_MST ADD CONSTRAINT FK_EMP_WARD FOREIGN KEY (WARD_ID) REFERENCES HRD.HRD_WARD_MST (WARD_ID)');
  P_TRY('CREATE INDEX HRD.IDX_EMP_WARD ON HRD.HRD_EMPLOYEE_MST (WARD_ID)');

  -- DS-05 HRD_LEAVE_REQUEST
  P_ADD_COL('HRD_LEAVE_REQUEST', 'NO_OF_DAYS',           'NUMBER(5)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'WARD_ID',              'NUMBER(6)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'ASSIGNED_APPROVER_ID', 'NUMBER(10)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'ROUTED_AS',            'VARCHAR2(15)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'DECISION_REMARKS',     'VARCHAR2(500)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'CREATED_BY',           'VARCHAR2(100)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'CREATED_ON',           'DATE');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'MODIFIED_BY',          'VARCHAR2(100)');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'MODIFIED_ON',          'DATE');
  P_ADD_COL('HRD_LEAVE_REQUEST', 'ROW_VERSION',          'NUMBER(9) DEFAULT 1 NOT NULL');

  P_TRY('ALTER TABLE HRD.HRD_LEAVE_REQUEST ADD CONSTRAINT FK_LVREQ_WARD FOREIGN KEY (WARD_ID) REFERENCES HRD.HRD_WARD_MST (WARD_ID)');
  P_TRY('ALTER TABLE HRD.HRD_LEAVE_REQUEST ADD CONSTRAINT FK_LVREQ_APPROVER FOREIGN KEY (ASSIGNED_APPROVER_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID)');
  -- NOVALIDATE: existing rows are not checked (their LEAVE_TYPE codes and STATUS values are not known); new rows are.
  P_TRY('ALTER TABLE HRD.HRD_LEAVE_REQUEST ADD CONSTRAINT FK_LVREQ_TYPE FOREIGN KEY (LEAVE_TYPE) REFERENCES HRD.HRD_LEAVE_TYPE_MST (LEAVE_TYPE) ENABLE NOVALIDATE');
  P_TRY('ALTER TABLE HRD.HRD_LEAVE_REQUEST ADD CONSTRAINT CK_LVREQ_STATUS CHECK (STATUS IN (''SUBMITTED'',''APPROVED'',''REJECTED'')) ENABLE NOVALIDATE');
  P_TRY('ALTER TABLE HRD.HRD_LEAVE_REQUEST ADD CONSTRAINT CK_LVREQ_DATES CHECK (TO_DATE >= FROM_DATE) ENABLE NOVALIDATE');
  P_TRY('ALTER TABLE HRD.HRD_LEAVE_REQUEST ADD CONSTRAINT CK_LVREQ_ROUTED CHECK (ROUTED_AS IN (''WARD_HEAD'',''DNS'',''REPORTING_MGR'')) ENABLE NOVALIDATE');

  P_TRY('CREATE INDEX HRD.IDX_LVREQ_EMP_FROM ON HRD.HRD_LEAVE_REQUEST (EMPLOYEE_ID, FROM_DATE)');
  P_TRY('CREATE INDEX HRD.IDX_LVREQ_APPR_STATUS ON HRD.HRD_LEAVE_REQUEST (ASSIGNED_APPROVER_ID, STATUS)');
  P_TRY('CREATE INDEX HRD.IDX_LVREQ_WARD_FROM ON HRD.HRD_LEAVE_REQUEST (WARD_ID, FROM_DATE)');
  P_TRY('CREATE INDEX HRD.IDX_LVREQ_STATUS_DATES ON HRD.HRD_LEAVE_REQUEST (STATUS, FROM_DATE, TO_DATE)');
END;
/
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.NO_OF_DAYS IS 'Calendar days from FROM_DATE to TO_DATE inclusive (PKG_LEAVE_MANAGEMENT.F_CALC_DAYS)';
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.WARD_ID IS 'Ward of the applicant at submission time (kept for reporting even if the employee moves)';
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.ASSIGNED_APPROVER_ID IS 'Employee who must decide the request (resolved at submission)';
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.ROUTED_AS IS 'WARD_HEAD, DNS (fallback) or REPORTING_MGR (routing mode)';
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.APPROVED_BY IS 'Employee who took the decision (approve OR reject)';
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.APPROVED_ON IS 'Date/time of the decision (approve OR reject)';
COMMENT ON COLUMN HRD.HRD_LEAVE_REQUEST.ROW_VERSION IS 'Incremented on every update; used for optimistic locking';
COMMENT ON COLUMN HRD.HRD_EMPLOYEE_MST.WARD_ID IS 'Ward the employee is assigned to (nursing staff)';

------------------------------------------------------------------------------
-- 4. Triggers (DS-10)
------------------------------------------------------------------------------
-- Existing TRG_LEAVE_REQUEST_BI is replaced: same ID behaviour plus audit columns.

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_REQUEST_BI BEFORE INSERT ON HRD.HRD_LEAVE_REQUEST FOR EACH ROW
BEGIN
  :NEW.LEAVE_REQUEST_ID := NVL(:NEW.LEAVE_REQUEST_ID, HRD.LEAVE_REQ_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
  :NEW.ROW_VERSION := 1;
END TRG_LEAVE_REQUEST_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_REQUEST_BU BEFORE UPDATE ON HRD.HRD_LEAVE_REQUEST FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
  :NEW.ROW_VERSION := :OLD.ROW_VERSION + 1;
END TRG_LEAVE_REQUEST_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_REQUEST_BD BEFORE DELETE ON HRD.HRD_LEAVE_REQUEST FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20199, 'Leave requests cannot be deleted (NFR-DAT-01)');
END TRG_LEAVE_REQUEST_BD;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_TYPE_MST_BI BEFORE INSERT ON HRD.HRD_LEAVE_TYPE_MST FOR EACH ROW
BEGIN
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_LEAVE_TYPE_MST_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_TYPE_MST_BU BEFORE UPDATE ON HRD.HRD_LEAVE_TYPE_MST FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
END TRG_LEAVE_TYPE_MST_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_CONFIG_MST_BI BEFORE INSERT ON HRD.HRD_LEAVE_CONFIG_MST FOR EACH ROW
BEGIN
  :NEW.LEAVE_CONFIG_ID := NVL(:NEW.LEAVE_CONFIG_ID, HRD.LEAVE_CONFIG_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_LEAVE_CONFIG_MST_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_CONFIG_MST_BU BEFORE UPDATE ON HRD.HRD_LEAVE_CONFIG_MST FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
END TRG_LEAVE_CONFIG_MST_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_WARD_MST_BI BEFORE INSERT ON HRD.HRD_WARD_MST FOR EACH ROW
BEGIN
  :NEW.WARD_ID := NVL(:NEW.WARD_ID, HRD.WARD_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_WARD_MST_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_WARD_MST_BU BEFORE UPDATE ON HRD.HRD_WARD_MST FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
END TRG_WARD_MST_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_ATTACHMENT_DTL_BI BEFORE INSERT ON HRD.HRD_LEAVE_ATTACHMENT_DTL FOR EACH ROW
BEGIN
  :NEW.LEAVE_ATTACHMENT_ID := NVL(:NEW.LEAVE_ATTACHMENT_ID, HRD.LEAVE_ATTACHMENT_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_LEAVE_ATTACHMENT_DTL_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_ATTACHMENT_DTL_BU BEFORE UPDATE ON HRD.HRD_LEAVE_ATTACHMENT_DTL FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20199, 'Leave attachments cannot be changed (NFR-DAT-01)');
END TRG_LEAVE_ATTACHMENT_DTL_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_ATTACHMENT_DTL_BD BEFORE DELETE ON HRD.HRD_LEAVE_ATTACHMENT_DTL FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20199, 'Leave attachments cannot be deleted (NFR-DAT-01)');
END TRG_LEAVE_ATTACHMENT_DTL_BD;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_BALANCE_MST_BI BEFORE INSERT ON HRD.HRD_LEAVE_BALANCE_MST FOR EACH ROW
BEGIN
  :NEW.LEAVE_BALANCE_ID := NVL(:NEW.LEAVE_BALANCE_ID, HRD.LEAVE_BALANCE_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_LEAVE_BALANCE_MST_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_BALANCE_MST_BU BEFORE UPDATE ON HRD.HRD_LEAVE_BALANCE_MST FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
END TRG_LEAVE_BALANCE_MST_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_AUDIT_LOG_BI BEFORE INSERT ON HRD.HRD_LEAVE_AUDIT_LOG FOR EACH ROW
BEGIN
  :NEW.LEAVE_AUDIT_ID := NVL(:NEW.LEAVE_AUDIT_ID, HRD.LEAVE_AUDIT_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_LEAVE_AUDIT_LOG_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_AUDIT_LOG_BU BEFORE UPDATE ON HRD.HRD_LEAVE_AUDIT_LOG FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20199, 'Audit log is append-only');
END TRG_LEAVE_AUDIT_LOG_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_AUDIT_LOG_BD BEFORE DELETE ON HRD.HRD_LEAVE_AUDIT_LOG FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20199, 'Audit log is append-only');
END TRG_LEAVE_AUDIT_LOG_BD;
/

CREATE OR REPLACE TRIGGER HRD.TRG_APP_USER_MST_BI BEFORE INSERT ON HRD.HRD_APP_USER_MST FOR EACH ROW
BEGIN
  :NEW.APP_USER_ID := NVL(:NEW.APP_USER_ID, HRD.APP_USER_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_APP_USER_MST_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_APP_USER_MST_BU BEFORE UPDATE ON HRD.HRD_APP_USER_MST FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
END TRG_APP_USER_MST_BU;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_ROLE_DTL_BI BEFORE INSERT ON HRD.HRD_LEAVE_ROLE_DTL FOR EACH ROW
BEGIN
  :NEW.LEAVE_ROLE_ID := NVL(:NEW.LEAVE_ROLE_ID, HRD.LEAVE_ROLE_SEQ.NEXTVAL);
  :NEW.CREATED_BY := NVL(:NEW.CREATED_BY, COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')));
  :NEW.CREATED_ON := NVL(:NEW.CREATED_ON, SYSDATE);
END TRG_LEAVE_ROLE_DTL_BI;
/

CREATE OR REPLACE TRIGGER HRD.TRG_LEAVE_ROLE_DTL_BU BEFORE UPDATE ON HRD.HRD_LEAVE_ROLE_DTL FOR EACH ROW
BEGIN
  :NEW.MODIFIED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
  :NEW.MODIFIED_ON := SYSDATE;
END TRG_LEAVE_ROLE_DTL_BU;
/

