-- CR-YYYY-XXX_02_migration.sql : seed and backfill (Design v0.1, DRAFT). Re-runnable (MERGE / guarded updates).
-- Run after 01_ddl.sql. Review every value marked TBC with HR before running in production.
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

-- M1. Leave types. Codes already used in existing requests are preserved (name = code until HR renames them).
MERGE INTO HRD.HRD_LEAVE_TYPE_MST T
USING (SELECT DISTINCT LEAVE_TYPE AS CODE FROM HRD.HRD_LEAVE_REQUEST WHERE LEAVE_TYPE IS NOT NULL) S
   ON (T.LEAVE_TYPE = S.CODE)
 WHEN NOT MATCHED THEN INSERT (LEAVE_TYPE, LEAVE_TYPE_NAME, IS_ACTIVE) VALUES (S.CODE, S.CODE, 'Y');

-- M2. Policy parameters. Type codes 'SCK' and 'CAS' are TBC (Q-20): confirm with
--     SELECT DISTINCT LEAVE_TYPE FROM HRD.HRD_LEAVE_REQUEST, then adjust.
MERGE INTO HRD.HRD_LEAVE_TYPE_MST T
USING (SELECT 'SCK' AS CODE, 'Sick leave'   AS NAME, CAST(NULL AS NUMBER) AS MAX_D, 2    AS CERT_D FROM DUAL
       UNION ALL
       SELECT 'CAS', 'Casual leave', 3, CAST(NULL AS NUMBER) FROM DUAL) S
   ON (T.LEAVE_TYPE = S.CODE)
 WHEN MATCHED THEN UPDATE SET T.LEAVE_TYPE_NAME = S.NAME, T.MAX_DAYS_PER_REQUEST = S.MAX_D, T.CERT_REQUIRED_OVER_DAYS = S.CERT_D
 WHEN NOT MATCHED THEN INSERT (LEAVE_TYPE, LEAVE_TYPE_NAME, IS_ACTIVE, MAX_DAYS_PER_REQUEST, CERT_REQUIRED_OVER_DAYS)
                       VALUES (S.CODE, S.NAME, 'Y', S.MAX_D, S.CERT_D);

-- M3. Configuration. Values marked TBC depend on open questions. DNS_EMPLOYEE_ID is loaded by HR (Q-05/Q-06).
MERGE INTO HRD.HRD_LEAVE_CONFIG_MST T
USING (SELECT 'ROUTING_MODE' AS K, 'WARD_HEAD' AS V, 'WARD_HEAD (DNS view) or REPORTING_MGR (HR view). TBC: Q-01' AS D FROM DUAL UNION ALL
       SELECT 'CERT_ALLOWED_MIME', 'image/jpeg,image/png,application/pdf', 'Allowed certificate MIME types. TBC: Q-13' FROM DUAL UNION ALL
       SELECT 'CERT_MAX_BYTES', '5242880', 'Max certificate size in bytes (5 MB). TBC: Q-13' FROM DUAL UNION ALL
       SELECT 'BALANCE_COUNTS_PENDING', 'N', 'Y = pending (SUBMITTED) requests reduce the displayed balance. TBC: Q-07' FROM DUAL UNION ALL
       SELECT 'REJECT_REMARKS_MANDATORY', 'N', 'Y = remark required when rejecting. TBC: Q-14' FROM DUAL) S
   ON (T.CONFIG_KEY = S.K)
 WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES (S.K, S.V, S.D);

-- M4. Backfill existing requests.
UPDATE HRD.HRD_LEAVE_REQUEST
   SET NO_OF_DAYS = TRUNC(TO_DATE) - TRUNC(FROM_DATE) + 1
 WHERE NO_OF_DAYS IS NULL AND TO_DATE >= FROM_DATE;

-- Existing pending requests: assume they went to the reporting manager (HR Manager statement M-03; verify, Q-15).
UPDATE HRD.HRD_LEAVE_REQUEST R
   SET ASSIGNED_APPROVER_ID = (SELECT E.REPORTING_MGR_ID FROM HRD.HRD_EMPLOYEE_MST E WHERE E.EMPLOYEE_ID = R.EMPLOYEE_ID),
       ROUTED_AS = 'REPORTING_MGR'
 WHERE R.STATUS = 'SUBMITTED' AND R.ASSIGNED_APPROVER_ID IS NULL;

UPDATE HRD.HRD_LEAVE_REQUEST R
   SET WARD_ID = (SELECT E.WARD_ID FROM HRD.HRD_EMPLOYEE_MST E WHERE E.EMPLOYEE_ID = R.EMPLOYEE_ID)
 WHERE R.WARD_ID IS NULL;   -- no-op until HR has loaded HRD_EMPLOYEE_MST.WARD_ID; re-run after the ward load

COMMIT;

-- M5. Validation (expected: all counts 0 except where HR data is still to be loaded)
SELECT 'REQUESTS_WITH_UNKNOWN_TYPE' AS CHECK_NAME, COUNT(*) AS CNT
  FROM HRD.HRD_LEAVE_REQUEST R WHERE NOT EXISTS (SELECT 1 FROM HRD.HRD_LEAVE_TYPE_MST T WHERE T.LEAVE_TYPE = R.LEAVE_TYPE)
UNION ALL
SELECT 'REQUESTS_WITH_NULL_OR_OTHER_STATUS', COUNT(*) FROM HRD.HRD_LEAVE_REQUEST WHERE STATUS IS NULL OR STATUS NOT IN ('SUBMITTED','APPROVED','REJECTED')
UNION ALL
SELECT 'PENDING_WITHOUT_APPROVER', COUNT(*) FROM HRD.HRD_LEAVE_REQUEST WHERE STATUS = 'SUBMITTED' AND ASSIGNED_APPROVER_ID IS NULL
UNION ALL
SELECT 'REQUESTS_WITH_TO_BEFORE_FROM', COUNT(*) FROM HRD.HRD_LEAVE_REQUEST WHERE TO_DATE < FROM_DATE;
