-- CR-2026-XXX-PEV_99_rollback.sql : rollback of Automated Employee Probation Evaluation (Design v0.1, DRAFT)
-- Reverse order of deployment. WARNING: drops all probation evaluation data created since go-live.
-- Export HRD_PROBATION_% tables first if the data must be kept.
-- EMPLOYEE_PROBATION_HISTORY / INFORMATION changes made by HR finalize are business data and are NOT reverted.
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

BEGIN DBMS_SCHEDULER.DROP_JOB('HRD.JOB_PROBATION_EVAL_QUEUE', TRUE); EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Remove pending-task registration (HIS.USER_ASSIGNMENT row inserted by 04_seed.sql) and alert rows here.
DROP PACKAGE HRD.PKG_PROBATION_EVALUATION;
-- PKG_PENDING_TASKS: redeploy the pre-change spec/body saved in 00_backup (P_PROBATION_EVAL_QUEUE removed).

DROP TABLE HRD.HRD_PROBATION_EVAL_HIS     PURGE;
DROP TABLE HRD.HRD_PROBATION_APPROVAL_TRN PURGE;
DROP TABLE HRD.HRD_PROBATION_EVAL_DTL     PURGE;
DROP TABLE HRD.HRD_PROBATION_EVAL_MST     PURGE;
DROP TABLE HRD.HRD_PROBATION_HIERARCHY_MST PURGE;
DROP TABLE HRD.HRD_PROBATION_CRITERIA_MST PURGE;
DROP TABLE HRD.HRD_PROBATION_JOB_LOG      PURGE;

DROP SEQUENCE HRD.PROBATION_EVAL_SEQ;
DROP SEQUENCE HRD.PROBATION_CRITERIA_SEQ;
DROP SEQUENCE HRD.PROBATION_EVAL_DTL_SEQ;
DROP SEQUENCE HRD.PROBATION_HIERARCHY_SEQ;
DROP SEQUENCE HRD.PROBATION_APPROVAL_SEQ;
DROP SEQUENCE HRD.PROBATION_EVAL_HIS_SEQ;
DROP SEQUENCE HRD.PROBATION_JOB_LOG_SEQ;
