-- CR-2026-XXX-PEV_01_ddl.sql : DDL for Automated Employee Probation Evaluation (Design v0.4, DRAFT)
-- Target: Oracle 19c+, schema HRD. Run as HRD (or a DBA with ALTER SESSION SET CURRENT_SCHEMA = HRD).
-- Run once on a clean schema; pre-check (Design 12.1 step 0) must return 0 rows for all new object names.
-- Rollback: CR-2026-XXX-PEV_99_rollback.sql
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

------------------------------------------------------------------------------
-- 1. Sequences (DS-08)
------------------------------------------------------------------------------
CREATE SEQUENCE HRD.PROBATION_EVAL_SEQ      START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_CRITERIA_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_CRITERIA_DTL_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_ASSIGNMENT_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_TRAINING_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_HIERARCHY_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_APPROVAL_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_EVAL_HIS_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE HRD.PROBATION_JOB_LOG_SEQ   START WITH 1 INCREMENT BY 1 NOCYCLE;

------------------------------------------------------------------------------
-- 2. Tables
------------------------------------------------------------------------------
-- DS-02a Standard evaluation criteria (setup, maintained by HR) (FR-024)
CREATE TABLE HRD.HRD_PROBATION_CRITERIA_MST (
  CRITERIA_ID        NUMBER(5)      NOT NULL,
  PARAMETER_NAME     VARCHAR2(100)  NOT NULL,
  DESCRIPTION        VARCHAR2(500),
  SORT_ORDER         NUMBER(3)      NOT NULL,
  MANDATORY          CHAR(1)        DEFAULT 'Y' NOT NULL,
  ACTIVE             CHAR(1)        DEFAULT 'Y' NOT NULL,
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_CRITERIA_MST PRIMARY KEY (CRITERIA_ID),
  CONSTRAINT UK_PROB_CRITERIA_NAME UNIQUE (PARAMETER_NAME),
  CONSTRAINT CK_PROB_CRITERIA_MAND CHECK (MANDATORY IN ('Y','N')),
  CONSTRAINT CK_PROB_CRITERIA_ACTIVE CHECK (ACTIVE IN ('Y','N'))
);
COMMENT ON TABLE HRD.HRD_PROBATION_CRITERIA_MST IS 'CR-2026-XXX-PEV: standard probation evaluation parameters (Evaluation Criteria tab)';

-- DS-04 Approval hierarchy (setup)
CREATE TABLE HRD.HRD_PROBATION_HIERARCHY_MST (
  PROBATION_HIERARCHY_ID NUMBER(6)     NOT NULL,
  DEPARTMENT_ID          VARCHAR2(7)   NOT NULL,
  LEVEL_NO               NUMBER(2)     NOT NULL,
  APPROVER_SOURCE        VARCHAR2(3)   NOT NULL,
  APPROVER_MRNO          VARCHAR2(14),
  ACTIVE                 CHAR(1)       DEFAULT 'Y' NOT NULL,
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_HIERARCHY_MST PRIMARY KEY (PROBATION_HIERARCHY_ID),
  CONSTRAINT FK_PROB_HIER_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEFINITIONS.DEPARTMENT (DEPARTMENT_ID),
  CONSTRAINT FK_PROB_HIER_APPROVER FOREIGN KEY (APPROVER_MRNO) REFERENCES HRD.INFORMATION (MRNO),
  CONSTRAINT CK_PROB_HIER_LEVEL CHECK (LEVEL_NO BETWEEN 1 AND 9),
  CONSTRAINT CK_PROB_HIER_SOURCE CHECK (APPROVER_SOURCE IN ('SUP','DH','DM','EMP')),
  CONSTRAINT CK_PROB_HIER_EMP CHECK (APPROVER_SOURCE <> 'EMP' OR APPROVER_MRNO IS NOT NULL),
  CONSTRAINT CK_PROB_HIER_ACTIVE CHECK (ACTIVE IN ('Y','N'))
);
-- RULE-14: departments with no rows here follow the organizational leave hierarchy (LEAVE_QUEUE_HIERARCHY / supervisor chain)
CREATE UNIQUE INDEX HRD.IDX_PROB_HIER_DEPT_LEVEL ON HRD.HRD_PROBATION_HIERARCHY_MST (DEPARTMENT_ID, LEVEL_NO);
COMMENT ON TABLE HRD.HRD_PROBATION_HIERARCHY_MST IS 'CR-2026-XXX-PEV: department probation approval levels (SUP=employee supervisor, DH=department head, DM=department manager, EMP=named employee e.g. director); departments not yet set up use the generic leave hierarchy';

-- DS-01 Evaluation header
CREATE TABLE HRD.HRD_PROBATION_EVAL_MST (
  PROBATION_EVAL_ID      NUMBER(12)     NOT NULL,
  EVAL_NO                VARCHAR2(20)   NOT NULL,
  MRNO                   VARCHAR2(14)   NOT NULL,
  PROB_START_DATE        DATE           NOT NULL,
  PROB_END_DATE          DATE           NOT NULL,
  DEPARTMENT_ID          VARCHAR2(7)    NOT NULL,
  EVALUATOR_MRNO         VARCHAR2(14),
  EVAL_STATUS            VARCHAR2(2)    DEFAULT 'EP' NOT NULL,
  CURRENT_LEVEL_NO       NUMBER(2),
  CURRENT_APPROVER_MRNO  VARCHAR2(14),
  ROUTE_SOURCE           VARCHAR2(3),
  RECOMMENDATION         CHAR(1),
  EXTEND_DAYS            NUMBER(4),
  NON_CONFIRM_REASONS    VARCHAR2(4000),
  TOTAL_SCORE            NUMBER(5),
  OBTAINED_SCORE         NUMBER(5),
  PERFORMANCE_PCT        NUMBER(5,2),
  SUBMITTED_DATE         DATE,
  HR_DECISION            CHAR(1),
  HR_EXTEND_DAYS         NUMBER(4),
  EXTENSION_REASON_ID    VARCHAR2(3),
  HR_DECISION_BY         VARCHAR2(14),
  HR_DECISION_DATE       DATE,
  HR_REMARKS             VARCHAR2(4000),
  EXCEPTION_REASON       VARCHAR2(200),
  VERSION_NO             NUMBER(6)      DEFAULT 1 NOT NULL,
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_EVAL_MST PRIMARY KEY (PROBATION_EVAL_ID),
  CONSTRAINT UK_PROB_EVAL_NO UNIQUE (EVAL_NO),
  CONSTRAINT FK_PROB_EVAL_EMP FOREIGN KEY (MRNO) REFERENCES HRD.INFORMATION (MRNO),
  CONSTRAINT FK_PROB_EVAL_PERIOD FOREIGN KEY (MRNO, PROB_START_DATE) REFERENCES HRD.EMPLOYEE_PROBATION_HISTORY (MRNO, START_DATE),
  CONSTRAINT FK_PROB_EVAL_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEFINITIONS.DEPARTMENT (DEPARTMENT_ID),
  CONSTRAINT FK_PROB_EVAL_EVALUATOR FOREIGN KEY (EVALUATOR_MRNO) REFERENCES HRD.INFORMATION (MRNO),
  CONSTRAINT FK_PROB_EVAL_REASON FOREIGN KEY (EXTENSION_REASON_ID) REFERENCES HRD.PROBATION_REASONS (PROBATION_REASON_ID),
  CONSTRAINT CK_PROB_EVAL_ROUTE CHECK (ROUTE_SOURCE IS NULL OR ROUTE_SOURCE IN ('PH','LQH','SUP')),
  CONSTRAINT CK_PROB_EVAL_STATUS CHECK (EVAL_STATUS IN ('EP','DR','PA','RT','FH','CM','CN')),
  CONSTRAINT CK_PROB_EVAL_RECOMM CHECK (RECOMMENDATION IS NULL OR RECOMMENDATION IN ('C','E','N')),
  CONSTRAINT CK_PROB_EVAL_EXT_DAYS CHECK (EXTEND_DAYS IS NULL OR EXTEND_DAYS > 0),
  CONSTRAINT CK_PROB_EVAL_HR_DEC CHECK (HR_DECISION IS NULL OR HR_DECISION IN ('C','E','O')),
  CONSTRAINT CK_PROB_EVAL_HR_EXT CHECK (HR_DECISION IS NULL OR HR_DECISION <> 'E' OR (HR_EXTEND_DAYS > 0 AND EXTENSION_REASON_ID IS NOT NULL)),
  CONSTRAINT CK_PROB_EVAL_SELF CHECK (EVALUATOR_MRNO IS NULL OR EVALUATOR_MRNO <> MRNO),
  CONSTRAINT CK_PROB_EVAL_PCT CHECK (PERFORMANCE_PCT IS NULL OR PERFORMANCE_PCT BETWEEN 0 AND 100),
  -- RULE-12: once submitted, a non-confirm recommendation must carry reasons (evidence count is checked in P_SUBMIT)
  CONSTRAINT CK_PROB_EVAL_REASONS CHECK (EVAL_STATUS IN ('EP','DR','RT','CN') OR RECOMMENDATION = 'C' OR NON_CONFIRM_REASONS IS NOT NULL)
);
COMMENT ON TABLE  HRD.HRD_PROBATION_EVAL_MST IS 'CR-2026-XXX-PEV: one row per probation evaluation (workflow header)';
COMMENT ON COLUMN HRD.HRD_PROBATION_EVAL_MST.EVAL_STATUS IS 'EP=Evaluation Pending, DR=Draft, PA=Pending Approval, RT=Returned, FH=Forwarded to HR, CM=Completed, CN=Cancelled';
COMMENT ON COLUMN HRD.HRD_PROBATION_EVAL_MST.EVALUATOR_MRNO IS 'Supervisor (HRD.INFORMATION.MANAGER_MRNO at creation); NULL = on HR exception list';
COMMENT ON COLUMN HRD.HRD_PROBATION_EVAL_MST.NON_CONFIRM_REASONS IS 'Specific reasons and observations when not recommended for confirmation (RULE-12); evidence in HRD.EMPLOYEE_PROBATION_ATTACHMENT';
COMMENT ON COLUMN HRD.HRD_PROBATION_EVAL_MST.TOTAL_SCORE IS '(Number of criteria + number of assignments) x 5 (RULE-13)';
COMMENT ON COLUMN HRD.HRD_PROBATION_EVAL_MST.ROUTE_SOURCE IS 'PH=department probation hierarchy, LQH=department leave hierarchy, SUP=supervisor chain with leave authority (RULE-14)';
COMMENT ON COLUMN HRD.HRD_PROBATION_EVAL_MST.VERSION_NO IS 'Optimistic lock; incremented on every update (NFR-DAT-03)';
-- RULE-03: one non-cancelled evaluation per employee probation period
CREATE UNIQUE INDEX HRD.IDX_PROB_EVAL_ACTIVE_UK ON HRD.HRD_PROBATION_EVAL_MST
  (CASE WHEN EVAL_STATUS <> 'CN' THEN MRNO END, CASE WHEN EVAL_STATUS <> 'CN' THEN PROB_START_DATE END);
CREATE INDEX HRD.IDX_PROB_EVAL_STATUS    ON HRD.HRD_PROBATION_EVAL_MST (EVAL_STATUS);
CREATE INDEX HRD.IDX_PROB_EVAL_EVALUATOR ON HRD.HRD_PROBATION_EVAL_MST (EVALUATOR_MRNO, EVAL_STATUS);
CREATE INDEX HRD.IDX_PROB_EVAL_APPROVER  ON HRD.HRD_PROBATION_EVAL_MST (CURRENT_APPROVER_MRNO, EVAL_STATUS);
CREATE INDEX HRD.IDX_PROB_EVAL_END_DATE  ON HRD.HRD_PROBATION_EVAL_MST (PROB_END_DATE);
CREATE INDEX HRD.IDX_PROB_EVAL_DEPT      ON HRD.HRD_PROBATION_EVAL_MST (DEPARTMENT_ID);
CREATE INDEX HRD.IDX_PROB_EVAL_REASON    ON HRD.HRD_PROBATION_EVAL_MST (EXTENSION_REASON_ID);

-- DS-02b Rating per criterion per evaluation (FR-024)
CREATE TABLE HRD.HRD_PROBATION_CRITERIA_DTL (
  PROBATION_CRITERIA_DTL_ID NUMBER(12)  NOT NULL,
  PROBATION_EVAL_ID         NUMBER(12)  NOT NULL,
  CRITERIA_ID               NUMBER(5)   NOT NULL,
  RATING                    NUMBER(1),
  REMARKS                   VARCHAR2(1000),
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_CRITERIA_DTL PRIMARY KEY (PROBATION_CRITERIA_DTL_ID),
  CONSTRAINT UK_PROB_CRITERIA_DTL UNIQUE (PROBATION_EVAL_ID, CRITERIA_ID),
  CONSTRAINT FK_PROB_CDTL_EVAL FOREIGN KEY (PROBATION_EVAL_ID) REFERENCES HRD.HRD_PROBATION_EVAL_MST (PROBATION_EVAL_ID),
  CONSTRAINT FK_PROB_CDTL_CRITERIA FOREIGN KEY (CRITERIA_ID) REFERENCES HRD.HRD_PROBATION_CRITERIA_MST (CRITERIA_ID),
  CONSTRAINT CK_PROB_CDTL_RATING CHECK (RATING IS NULL OR RATING BETWEEN 1 AND 5)
);
CREATE INDEX HRD.IDX_PROB_CDTL_CRITERIA ON HRD.HRD_PROBATION_CRITERIA_DTL (CRITERIA_ID);
COMMENT ON TABLE HRD.HRD_PROBATION_CRITERIA_DTL IS 'CR-2026-XXX-PEV: rating (1-5) and remarks per standard criterion';

-- DS-02 Assignments completed during the probationary period, rated 1-5 (FR-021)
CREATE TABLE HRD.HRD_PROBATION_ASSIGNMENT_DTL (
  PROBATION_ASSIGNMENT_ID NUMBER(12)    NOT NULL,
  PROBATION_EVAL_ID       NUMBER(12)    NOT NULL,
  SORT_ORDER              NUMBER(3)     NOT NULL,
  ASSIGNMENT_DESC         VARCHAR2(500) NOT NULL,
  RATING                  NUMBER(1),
  REMARKS                 VARCHAR2(1000),
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_ASSIGNMENT_DTL PRIMARY KEY (PROBATION_ASSIGNMENT_ID),
  CONSTRAINT FK_PROB_ASSIGN_EVAL FOREIGN KEY (PROBATION_EVAL_ID) REFERENCES HRD.HRD_PROBATION_EVAL_MST (PROBATION_EVAL_ID),
  CONSTRAINT CK_PROB_ASSIGN_RATING CHECK (RATING IS NULL OR RATING BETWEEN 1 AND 5)
);
CREATE INDEX HRD.IDX_PROB_ASSIGN_EVAL ON HRD.HRD_PROBATION_ASSIGNMENT_DTL (PROBATION_EVAL_ID, SORT_ORDER);
COMMENT ON TABLE HRD.HRD_PROBATION_ASSIGNMENT_DTL IS 'CR-2026-XXX-PEV: assignments completed during probation, each rated 1 (Very Low) to 5 (Very High)';

-- DS-03 Employee's assessed training needs (FR-022)
CREATE TABLE HRD.HRD_PROBATION_TRAINING_DTL (
  PROBATION_TRAINING_ID   NUMBER(12)    NOT NULL,
  PROBATION_EVAL_ID       NUMBER(12)    NOT NULL,
  SORT_ORDER              NUMBER(3)     NOT NULL,
  TRAINING_NEED           VARCHAR2(500) NOT NULL,
  REMARKS                 VARCHAR2(1000),
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_TRAINING_DTL PRIMARY KEY (PROBATION_TRAINING_ID),
  CONSTRAINT FK_PROB_TRAIN_EVAL FOREIGN KEY (PROBATION_EVAL_ID) REFERENCES HRD.HRD_PROBATION_EVAL_MST (PROBATION_EVAL_ID)
);
CREATE INDEX HRD.IDX_PROB_TRAIN_EVAL ON HRD.HRD_PROBATION_TRAINING_DTL (PROBATION_EVAL_ID, SORT_ORDER);
COMMENT ON TABLE HRD.HRD_PROBATION_TRAINING_DTL IS 'CR-2026-XXX-PEV: employee assessed training needs recorded by the evaluator';

-- Evidence (FR-023): reuse existing HRD.EMPLOYEE_PROBATION_ATTACHMENT (SR_NO, MRNO, START_DATE, DOCUMENT_ID,
-- DOCUMENT_DESCRIPTION, REMARKS, ATTACHED_BY, DOCUMENT_TYPE_ID). No DDL change; rows are written by
-- PKG_PROBATION_EVALUATION.P_ADD_EVIDENCE with START_DATE = HRD_PROBATION_EVAL_MST.PROB_START_DATE.

-- DS-05 Approval actions per level
CREATE TABLE HRD.HRD_PROBATION_APPROVAL_TRN (
  PROBATION_APPROVAL_ID  NUMBER(12)     NOT NULL,
  PROBATION_EVAL_ID      NUMBER(12)     NOT NULL,
  LEVEL_NO               NUMBER(2)      NOT NULL,
  APPROVER_MRNO          VARCHAR2(14)   NOT NULL,
  ACTING_FOR_MRNO        VARCHAR2(14),
  ACTION                 CHAR(1)        DEFAULT 'P' NOT NULL,
  ACTION_DATE            DATE,
  COMMENTS               VARCHAR2(4000),
  USER_ID            VARCHAR2(30),
  TERMINAL           VARCHAR2(30),
  TRN_DATE           DATE,
  ORIGINAL_USER_ID   VARCHAR2(30),
  ORIGINAL_TERMINAL  VARCHAR2(30),
  ORIGINAL_TRN_DATE  DATE,
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  WS_SYNC_DATE       DATE,
  CONSTRAINT PK_HRD_PROBATION_APPROVAL_TRN PRIMARY KEY (PROBATION_APPROVAL_ID),
  CONSTRAINT FK_PROB_APPR_EVAL FOREIGN KEY (PROBATION_EVAL_ID) REFERENCES HRD.HRD_PROBATION_EVAL_MST (PROBATION_EVAL_ID),
  CONSTRAINT CK_PROB_APPR_ACTION CHECK (ACTION IN ('P','A','R','S')),
  CONSTRAINT CK_PROB_APPR_RETURN CHECK (ACTION <> 'R' OR COMMENTS IS NOT NULL)
);
CREATE INDEX HRD.IDX_PROB_APPR_EVAL ON HRD.HRD_PROBATION_APPROVAL_TRN (PROBATION_EVAL_ID, LEVEL_NO);
COMMENT ON TABLE HRD.HRD_PROBATION_APPROVAL_TRN IS 'CR-2026-XXX-PEV: approval actions per level (P=Pending, A=Approved, R=Returned, S=Skipped)';

-- DS-06 Status history (insert-only)
CREATE TABLE HRD.HRD_PROBATION_EVAL_HIS (
  PROBATION_EVAL_HIS_ID  NUMBER(12)     NOT NULL,
  PROBATION_EVAL_ID      NUMBER(12)     NOT NULL,
  OLD_STATUS             VARCHAR2(2),
  NEW_STATUS             VARCHAR2(2)    NOT NULL,
  ACTION                 VARCHAR2(30)   NOT NULL,
  ACTION_BY              VARCHAR2(14)   NOT NULL,
  ACTION_DATE            DATE           DEFAULT SYSDATE NOT NULL,
  COMMENTS               VARCHAR2(4000),
  ORG_ID             VARCHAR2(3),
  ZON_ID             VARCHAR2(3),
  LOC_ID             VARCHAR2(3),
  CONSTRAINT PK_HRD_PROBATION_EVAL_HIS PRIMARY KEY (PROBATION_EVAL_HIS_ID),
  CONSTRAINT FK_PROB_HIS_EVAL FOREIGN KEY (PROBATION_EVAL_ID) REFERENCES HRD.HRD_PROBATION_EVAL_MST (PROBATION_EVAL_ID)
);
CREATE INDEX HRD.IDX_PROB_HIS_EVAL ON HRD.HRD_PROBATION_EVAL_HIS (PROBATION_EVAL_ID, ACTION_DATE);
COMMENT ON TABLE HRD.HRD_PROBATION_EVAL_HIS IS 'CR-2026-XXX-PEV: insert-only status history (NFR-AUD-02)';

-- DS-07 Daily job run log
CREATE TABLE HRD.HRD_PROBATION_JOB_LOG (
  PROBATION_JOB_LOG_ID   NUMBER(12)     NOT NULL,
  RUN_START              DATE           NOT NULL,
  RUN_END                DATE,
  EMPLOYEES_SCANNED      NUMBER(7),
  QUEUES_CREATED         NUMBER(7),
  EXCEPTIONS             NUMBER(7),
  CANCELLED              NUMBER(7),
  RUN_STATUS             VARCHAR2(10)   NOT NULL,
  ERROR_MSG              VARCHAR2(4000),
  CONSTRAINT PK_HRD_PROBATION_JOB_LOG PRIMARY KEY (PROBATION_JOB_LOG_ID),
  CONSTRAINT CK_PROB_JOB_STATUS CHECK (RUN_STATUS IN ('RUNNING','SUCCESS','FAILED'))
);
COMMENT ON TABLE HRD.HRD_PROBATION_JOB_LOG IS 'CR-2026-XXX-PEV: run log of the daily probation queue job (NFR-OPS-01)';

------------------------------------------------------------------------------
-- 3. Audit triggers (DS-08) - same pattern as HRD.EMPLOYEE_PROBATION_HISTORY_INS / _UPD
------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER HRD.TRG_PROBATION_EVAL_MST_BI
  BEFORE INSERT ON HRD.HRD_PROBATION_EVAL_MST
  FOR EACH ROW
DECLARE
  V_TERMINAL VARCHAR2(100) := SECURITY.GET_TERMINAL;
  V_USER_ID  VARCHAR2(100) := SECURITY.CURRENTUSER(V_TERMINAL);
BEGIN
  IF SECURITY.F_WS_USER() THEN
    RETURN;
  END IF;
  :NEW.ORIGINAL_USER_ID  := V_USER_ID;
  :NEW.ORIGINAL_TERMINAL := V_TERMINAL;
  :NEW.ORIGINAL_TRN_DATE := SYSDATE;
  HIS.P_GET_CONTEXT_COL(P_ORGANIZATION_ID => :NEW.ORG_ID,
                        P_ZONE_ID         => :NEW.ZON_ID,
                        P_LOCATION_ID     => :NEW.LOC_ID);
END;
/
CREATE OR REPLACE TRIGGER HRD.TRG_PROBATION_EVAL_MST_BU
  BEFORE UPDATE ON HRD.HRD_PROBATION_EVAL_MST
  FOR EACH ROW
DECLARE
  V_TERMINAL VARCHAR2(100) := SECURITY.GET_TERMINAL;
  V_USER_ID  VARCHAR2(100) := SECURITY.CURRENTUSER(V_TERMINAL);
BEGIN
  IF SECURITY.F_WS_USER() THEN
    RETURN;
  END IF;
  :NEW.USER_ID    := V_USER_ID;
  :NEW.TERMINAL   := V_TERMINAL;
  :NEW.TRN_DATE   := SYSDATE;
  :NEW.VERSION_NO := :OLD.VERSION_NO + 1;
END;
/
-- Same BI/BU pair (without VERSION_NO) for: HRD_PROBATION_CRITERIA_MST, HRD_PROBATION_CRITERIA_DTL,
-- HRD_PROBATION_HIERARCHY_MST, HRD_PROBATION_ASSIGNMENT_DTL,
-- HRD_PROBATION_TRAINING_DTL, HRD_PROBATION_APPROVAL_TRN -> TRG_PROBATION_HIERARCHY_MST_BI/_BU,
-- TRG_PROBATION_ASSIGNMENT_DTL_BI/_BU, TRG_PROBATION_TRAINING_DTL_BI/_BU, TRG_PROBATION_APPROVAL_TRN_BI/_BU.
-- Developer: generate them from the two triggers above (skmch-dev-implement).

-- History is insert-only (NFR-AUD-02)
CREATE OR REPLACE TRIGGER HRD.TRG_PROBATION_EVAL_HIS_BUD
  BEFORE UPDATE OR DELETE ON HRD.HRD_PROBATION_EVAL_HIS
BEGIN
  RAISE_APPLICATION_ERROR(-20890, 'Probation evaluation history cannot be changed or deleted.');
END;
/
