--------------------------------------------------------------------------------
-- Staff Lounge Usage Tracking & Payroll Deduction
-- 01 - Sequences, tables, constraints, indexes
--
-- Assumes the existing HR employee master HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID PK).
--------------------------------------------------------------------------------

----------------------------------------
-- Sequences
----------------------------------------
CREATE SEQUENCE HRD.LOUNGE_CHARGE_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.LOUNGE_CARD_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRD.LOUNGE_SWIPE_SEQ      START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE HRD.LOUNGE_SWIPE_ERR_SEQ  START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HRD.LOUNGE_AUDIT_SEQ      START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE HRD.LOUNGE_DEDUCTION_SEQ  START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HRD.LOUNGE_DAY_RPT_SEQ    START WITH 1 INCREMENT BY 1 CACHE 100;

----------------------------------------
-- Charge master: rate per swipe type.
-- Seeded with 600 for CHECK_IN and 600 for CHECK_OUT.
-- The rate in force at swipe time is copied onto the transaction row,
-- so later rate changes never alter already-recorded charges.
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_CHARGE_MST
(
    LOUNGE_CHARGE_ID   NUMBER         DEFAULT HRD.LOUNGE_CHARGE_SEQ.NEXTVAL NOT NULL,
    SWIPE_TYPE         VARCHAR2(10)   NOT NULL,
    CHARGE_AMOUNT      NUMBER(12,2)   NOT NULL,
    EFFECTIVE_FROM     DATE           NOT NULL,
    EFFECTIVE_TO       DATE,
    CREATED_BY         VARCHAR2(255)  NOT NULL,
    CREATED_ON         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR2(255),
    UPDATED_ON         TIMESTAMP,
    CONSTRAINT HRD_LOUNGE_CHARGE_MST_PK  PRIMARY KEY (LOUNGE_CHARGE_ID),
    CONSTRAINT HRD_LOUNGE_CHARGE_TYPE_CK CHECK (SWIPE_TYPE IN ('CHECK_IN', 'CHECK_OUT')),
    CONSTRAINT HRD_LOUNGE_CHARGE_AMT_CK  CHECK (CHARGE_AMOUNT >= 0),
    CONSTRAINT HRD_LOUNGE_CHARGE_DT_CK   CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);

COMMENT ON TABLE  HRD.HRD_LOUNGE_CHARGE_MST               IS 'Staff lounge charge rate per swipe type';
COMMENT ON COLUMN HRD.HRD_LOUNGE_CHARGE_MST.SWIPE_TYPE    IS 'CHECK_IN or CHECK_OUT';
COMMENT ON COLUMN HRD.HRD_LOUNGE_CHARGE_MST.CHARGE_AMOUNT IS 'Amount charged for each swipe of this type';

----------------------------------------
-- Card master: maps a physical lounge card to an employee.
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_CARD_MST
(
    LOUNGE_CARD_ID     NUMBER         DEFAULT HRD.LOUNGE_CARD_SEQ.NEXTVAL NOT NULL,
    CARD_NO            VARCHAR2(50)   NOT NULL,
    EMPLOYEE_ID        NUMBER         NOT NULL,
    IS_ACTIVE          VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    ISSUED_ON          DATE           DEFAULT TRUNC(SYSDATE) NOT NULL,
    BLOCKED_ON         DATE,
    CREATED_BY         VARCHAR2(255)  NOT NULL,
    CREATED_ON         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR2(255),
    UPDATED_ON         TIMESTAMP,
    CONSTRAINT HRD_LOUNGE_CARD_MST_PK   PRIMARY KEY (LOUNGE_CARD_ID),
    CONSTRAINT HRD_LOUNGE_CARD_NO_UK    UNIQUE (CARD_NO),
    CONSTRAINT HRD_LOUNGE_CARD_EMP_FK   FOREIGN KEY (EMPLOYEE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
    CONSTRAINT HRD_LOUNGE_CARD_ACT_CK   CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE INDEX HRD.IDX_LOUNGE_CARD_EMP ON HRD.HRD_LOUNGE_CARD_MST (EMPLOYEE_ID);

COMMENT ON TABLE HRD.HRD_LOUNGE_CARD_MST IS 'Staff lounge access cards issued to employees';

----------------------------------------
-- Swipe transactions: one row per successful check-in / check-out.
-- This is the table payroll reads to compute the deduction.
--
-- For very high volumes consider (Enterprise Edition + Partitioning):
--   PARTITION BY RANGE (SWIPE_TIMESTAMP) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_SWIPE_TRN
(
    LOUNGE_SWIPE_ID    NUMBER         DEFAULT HRD.LOUNGE_SWIPE_SEQ.NEXTVAL NOT NULL,
    EMPLOYEE_ID        NUMBER         NOT NULL,
    LOUNGE_CARD_ID     NUMBER         NOT NULL,
    LOUNGE_CODE        VARCHAR2(30)   DEFAULT 'MAIN' NOT NULL,
    DEVICE_ID          VARCHAR2(50),
    SWIPE_TYPE         VARCHAR2(10)   NOT NULL,
    SWIPE_TIMESTAMP    TIMESTAMP      NOT NULL,
    CHARGE_AMOUNT      NUMBER(12,2)   NOT NULL,
    STATUS             VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    PAYROLL_ID         NUMBER,
    DEDUCTED_ON        TIMESTAMP,
    REVERSAL_REASON    VARCHAR2(500),
    CREATED_BY         VARCHAR2(255)  NOT NULL,
    CREATED_ON         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR2(255),
    UPDATED_ON         TIMESTAMP,
    CONSTRAINT HRD_LOUNGE_SWIPE_TRN_PK   PRIMARY KEY (LOUNGE_SWIPE_ID),
    CONSTRAINT HRD_LOUNGE_SWIPE_EMP_FK   FOREIGN KEY (EMPLOYEE_ID)    REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
    CONSTRAINT HRD_LOUNGE_SWIPE_CARD_FK  FOREIGN KEY (LOUNGE_CARD_ID) REFERENCES HRD.HRD_LOUNGE_CARD_MST (LOUNGE_CARD_ID),
    CONSTRAINT HRD_LOUNGE_SWIPE_TYPE_CK  CHECK (SWIPE_TYPE IN ('CHECK_IN', 'CHECK_OUT')),
    CONSTRAINT HRD_LOUNGE_SWIPE_STAT_CK  CHECK (STATUS IN ('PENDING', 'DEDUCTED', 'REVERSED')),
    CONSTRAINT HRD_LOUNGE_SWIPE_AMT_CK   CHECK (CHARGE_AMOUNT >= 0),
    CONSTRAINT HRD_LOUNGE_SWIPE_DED_CK   CHECK (STATUS <> 'DEDUCTED' OR (PAYROLL_ID IS NOT NULL AND DEDUCTED_ON IS NOT NULL))
);

-- Payroll aggregation: pending charges per employee in a period
CREATE INDEX HRD.IDX_LOUNGE_SWIPE_STAT_TS  ON HRD.HRD_LOUNGE_SWIPE_TRN (STATUS, SWIPE_TIMESTAMP, EMPLOYEE_ID);
-- Employee history / duplicate-swipe check
CREATE INDEX HRD.IDX_LOUNGE_SWIPE_EMP_TS   ON HRD.HRD_LOUNGE_SWIPE_TRN (EMPLOYEE_ID, SWIPE_TIMESTAMP);
-- Day-end report
CREATE INDEX HRD.IDX_LOUNGE_SWIPE_TS       ON HRD.HRD_LOUNGE_SWIPE_TRN (SWIPE_TIMESTAMP);
-- Lookup by payroll run
CREATE INDEX HRD.IDX_LOUNGE_SWIPE_PAYROLL  ON HRD.HRD_LOUNGE_SWIPE_TRN (PAYROLL_ID);
CREATE INDEX HRD.IDX_LOUNGE_SWIPE_CARD     ON HRD.HRD_LOUNGE_SWIPE_TRN (LOUNGE_CARD_ID);

COMMENT ON TABLE  HRD.HRD_LOUNGE_SWIPE_TRN                 IS 'Staff lounge card swipe events and their charges';
COMMENT ON COLUMN HRD.HRD_LOUNGE_SWIPE_TRN.SWIPE_TYPE      IS 'CHECK_IN or CHECK_OUT';
COMMENT ON COLUMN HRD.HRD_LOUNGE_SWIPE_TRN.CHARGE_AMOUNT   IS 'Charge applied for this swipe (rate in force at swipe time)';
COMMENT ON COLUMN HRD.HRD_LOUNGE_SWIPE_TRN.STATUS          IS 'PENDING = awaiting payroll, DEDUCTED = deducted in PAYROLL_ID, REVERSED = cancelled by HR';
COMMENT ON COLUMN HRD.HRD_LOUNGE_SWIPE_TRN.PAYROLL_ID      IS 'Payroll run that deducted this charge';

----------------------------------------
-- Failed swipe log: rejected / erroneous swipes (unknown card, blocked card,
-- duplicate read, etc.). Written in an autonomous transaction.
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_SWIPE_ERR_LOG
(
    LOUNGE_SWIPE_ERR_ID NUMBER         DEFAULT HRD.LOUNGE_SWIPE_ERR_SEQ.NEXTVAL NOT NULL,
    CARD_NO             VARCHAR2(50),
    EMPLOYEE_ID         NUMBER,
    LOUNGE_CODE         VARCHAR2(30),
    DEVICE_ID           VARCHAR2(50),
    SWIPE_TYPE          VARCHAR2(30),
    SWIPE_TIMESTAMP     TIMESTAMP,
    ERROR_CODE          VARCHAR2(30)   NOT NULL,
    ERROR_MESSAGE       VARCHAR2(4000),
    CREATED_BY          VARCHAR2(255)  NOT NULL,
    CREATED_ON          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT HRD_LOUNGE_SWIPE_ERR_LOG_PK PRIMARY KEY (LOUNGE_SWIPE_ERR_ID)
);

CREATE INDEX HRD.IDX_LOUNGE_SWIPE_ERR_ON ON HRD.HRD_LOUNGE_SWIPE_ERR_LOG (CREATED_ON);

COMMENT ON TABLE HRD.HRD_LOUNGE_SWIPE_ERR_LOG IS 'Rejected / failed staff lounge card swipes';

----------------------------------------
-- Audit log: every insert / status change on swipe transactions.
-- Populated only by triggers; rows are never updated or deleted.
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_AUDIT_LOG
(
    LOUNGE_AUDIT_ID     NUMBER         DEFAULT HRD.LOUNGE_AUDIT_SEQ.NEXTVAL NOT NULL,
    LOUNGE_SWIPE_ID     NUMBER         NOT NULL,
    ACTION              VARCHAR2(10)   NOT NULL,
    OLD_STATUS          VARCHAR2(20),
    NEW_STATUS          VARCHAR2(20),
    OLD_CHARGE_AMOUNT   NUMBER(12,2),
    NEW_CHARGE_AMOUNT   NUMBER(12,2),
    PAYROLL_ID          NUMBER,
    REMARKS             VARCHAR2(500),
    ACTION_BY           VARCHAR2(255)  NOT NULL,
    ACTION_ON           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CLIENT_IP           VARCHAR2(50),
    CONSTRAINT HRD_LOUNGE_AUDIT_LOG_PK PRIMARY KEY (LOUNGE_AUDIT_ID),
    CONSTRAINT HRD_LOUNGE_AUDIT_ACT_CK CHECK (ACTION IN ('INSERT', 'UPDATE'))
);

CREATE INDEX HRD.IDX_LOUNGE_AUDIT_SWIPE ON HRD.HRD_LOUNGE_AUDIT_LOG (LOUNGE_SWIPE_ID);

COMMENT ON TABLE HRD.HRD_LOUNGE_AUDIT_LOG IS 'Audit trail of staff lounge charges and deductions';

----------------------------------------
-- Payroll deduction detail: one row per employee per payroll run.
-- This is the "amount to be deducted" handed to payroll.
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_DEDUCTION_DTL
(
    LOUNGE_DEDUCTION_ID NUMBER         DEFAULT HRD.LOUNGE_DEDUCTION_SEQ.NEXTVAL NOT NULL,
    PAYROLL_ID          NUMBER         NOT NULL,
    EMPLOYEE_ID         NUMBER         NOT NULL,
    PERIOD_FROM         DATE           NOT NULL,
    PERIOD_TO           DATE           NOT NULL,
    CHECK_IN_COUNT      NUMBER         NOT NULL,
    CHECK_OUT_COUNT     NUMBER         NOT NULL,
    DEDUCTION_AMOUNT    NUMBER(12,2)   NOT NULL,
    CREATED_BY          VARCHAR2(255)  NOT NULL,
    CREATED_ON          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT HRD_LOUNGE_DEDUCTION_DTL_PK PRIMARY KEY (LOUNGE_DEDUCTION_ID),
    CONSTRAINT HRD_LOUNGE_DED_PAY_EMP_UK   UNIQUE (PAYROLL_ID, EMPLOYEE_ID),
    CONSTRAINT HRD_LOUNGE_DED_EMP_FK       FOREIGN KEY (EMPLOYEE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID),
    CONSTRAINT HRD_LOUNGE_DED_AMT_CK       CHECK (DEDUCTION_AMOUNT >= 0)
);

CREATE INDEX HRD.IDX_LOUNGE_DED_EMP ON HRD.HRD_LOUNGE_DEDUCTION_DTL (EMPLOYEE_ID);

COMMENT ON TABLE HRD.HRD_LOUNGE_DEDUCTION_DTL IS 'Staff lounge amount deducted per employee per payroll run';

----------------------------------------
-- Day-end report: per employee per day usage summary.
----------------------------------------
CREATE TABLE HRD.HRD_LOUNGE_DAY_END_RPT
(
    LOUNGE_DAY_RPT_ID   NUMBER         DEFAULT HRD.LOUNGE_DAY_RPT_SEQ.NEXTVAL NOT NULL,
    REPORT_DATE         DATE           NOT NULL,
    EMPLOYEE_ID         NUMBER         NOT NULL,
    CHECK_IN_COUNT      NUMBER         NOT NULL,
    CHECK_OUT_COUNT     NUMBER         NOT NULL,
    FIRST_CHECK_IN      TIMESTAMP,
    LAST_CHECK_OUT      TIMESTAMP,
    TOTAL_CHARGE        NUMBER(12,2)   NOT NULL,
    GENERATED_BY        VARCHAR2(255)  NOT NULL,
    GENERATED_ON        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT HRD_LOUNGE_DAY_END_RPT_PK   PRIMARY KEY (LOUNGE_DAY_RPT_ID),
    CONSTRAINT HRD_LOUNGE_DAY_RPT_UK       UNIQUE (REPORT_DATE, EMPLOYEE_ID),
    CONSTRAINT HRD_LOUNGE_DAY_RPT_EMP_FK   FOREIGN KEY (EMPLOYEE_ID) REFERENCES HRD.HRD_EMPLOYEE_MST (EMPLOYEE_ID)
);

COMMENT ON TABLE HRD.HRD_LOUNGE_DAY_END_RPT IS 'Day-end staff lounge usage summary per employee';

----------------------------------------
-- Seed charges: 600 per check-in, 600 per check-out
----------------------------------------
INSERT INTO HRD.HRD_LOUNGE_CHARGE_MST (SWIPE_TYPE, CHARGE_AMOUNT, EFFECTIVE_FROM, CREATED_BY)
VALUES ('CHECK_IN',  600, DATE '2026-01-01', 'INSTALL');

INSERT INTO HRD.HRD_LOUNGE_CHARGE_MST (SWIPE_TYPE, CHARGE_AMOUNT, EFFECTIVE_FROM, CREATED_BY)
VALUES ('CHECK_OUT', 600, DATE '2026-01-01', 'INSTALL');

COMMIT;
